<?php if($this->links) : ?>
<div class="row">
    <?php foreach($this->links as $key => $link) : ?>
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <a target="_blank" href="<?php echo $link->url; ?>">
                <div class="row">
                    <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
                        <img src="<?php echo $this->basePath($link->image); ?>" class="img-responsive">
                    </div>

                    <div class="col-xs-8 col-sm-8 col-md-8 col-lg-8">
                        <p>
                            <?php echo $link->title; ?>
                        </p>
                    </div>
                </div>
            </a>
        </div>

        <?php if(($key + 1) == 1) : ?>
            <div class="visible-xs" style="margin-top: 20px;">&nbsp;</div>
        <?php endif; ?>

        <?php if(($key + 1) == 2) : ?>
            <div class="visible-xs visible-sm" style="margin-top: 20px;">&nbsp;</div>
        <?php endif; ?>

        <?php if(($key + 1) == 3) : ?>
            <div class="visible-xs visible-md visible-lg" style="margin-top: 20px;">&nbsp;</div>
        <?php endif; ?>
    <?php endforeach; ?>
</div>
<?php else : ?>
    <div class="alert alert-info" style="width: 100% !important; text-align: center;">
        <h3><i class="ezo-edit-1"></i></h3>
        <h4><?php echo $this->translate('Useful links will be added soon') ?></h4>
    </div>
<?php endif; ?>