<?php  
	$this->headTitle()->append($this->translate('Newsletter'));
?>
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-sm-4">
        <h2><?php echo $this->translate('Newsletter') ?></h2>
        <?php
            $this->plugin('navigation')->setContainer($this->navigation('Zend\Navigation\Admin')->getContainer());

            echo $this->navigation()
                      ->breadcrumbs()
                      ->setMinDepth(0)               
                      ->setMaxDepth(4)         
                      ->setPartial('partial/admin-breadcrumbs');
        ?>
    </div>
</div>
<div class="wrapper wrapper-content">
	<?php if($this->subscribers): ?>
		<div class="row">
			<div class="col-lg-12">
				<div class="ibox float-e-margins">
					<div class="ibox-title">
						<h5><?php echo $this->translate('Subscribers') ?></h5>
					</div>
					<div class="ibox-content table-reponsive">
						<table class="table datatable">
							<thead>
								<tr>
									<td>#</td>
									<td><?php echo $this->translate('Email') ?></td>
									<td>Delete</td>
								</tr>
							</thead>
							<tbody>
								<?php $i=1; foreach ($this->subscribers as $subscriber): ?>
									<tr>
										<td><?php echo $i ?></td>
										<td><?php echo $subscriber->email ?></td>
										<td>
											<a href="<?php echo $this->url('admin/newsletter', array(
												'locale' => $this->currentLocale(),
												'controller' => 'admin',
												'action' => 'delete',
												'link'	=> $subscriber->link,
											)); ?>">
												<i class="fa fa-trash"></i>
											</a>
										</td>
									</tr>
								<?php $i++; endforeach ?>
							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
	<?php else: ?>
		<div class="middle-box text-center alert alert-success">
			<p>
				<i class="fa fa-check fa-3x"></i>
			</p>
	        <h3 class="font-bold"><?php echo $this->translate('Nobody subscribed') ?></h3>
	    </div>
	<?php endif ?>
</div>
<script src="js/plugins/dataTables/jquery.dataTables.js"></script>
<script src="js/plugins/dataTables/dataTables.bootstrap.js"></script>
<script src="js/plugins/dataTables/dataTables.responsive.js"></script>
<script src="js/plugins/dataTables/dataTables.tableTools.min.js"></script>
<?php  
	$this->headStyle()
	->appendStyle("
		.white--space-nowrap
		{
			white-space: nowrap;
		}
	");

	$this->headLink()
	->appendStylesheet($this->basePath('css/plugins/dataTables/dataTables.bootstrap.css'))
	->appendStylesheet($this->basePath('css/plugins/dataTables/dataTables.responsive.css'))
	->appendStylesheet($this->basePath('css/plugins/dataTables/dataTables.tableTools.min.css'))
	->appendStylesheet($this->basePath('css/plugins/dataTables/dataTables.custom.css'));

	$this->inlineScript()
	->appendFile($this->basePath('js/plugins/dataTables/jquery.dataTables.js'))
	->appendFile($this->basePath('js/plugins/dataTables/dataTables.bootstrap.js'))
	->appendFile($this->basePath('js/plugins/dataTables/dataTables.responsive.js'))
	->appendFile($this->basePath('js/plugins/dataTables/dataTables.tableTools.min.js'))
	->appendScript("
		$('.datatable').dataTable({
            //'responsive': true,
            'language': {
                'url': '".$this->url('application/default', array('locale' => $this->currentLocale(), 'controller' => 'jsPlugins', 'action' => 'datatablesI18n'))."'
            }
        });
		$('*[data-toggle=\"tooltip\"]').tooltip();
	");
?>