<?php $this->headTitle()->append($this->translate('Feedback')) ?>
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-sm-8">
        <h2><?php echo $this->translate('Feedback') ?></h2>
        <?php
            echo $this->navigation('Zend\Navigation\Admin')
                      ->breadcrumbs()
                      ->setMinDepth(0)               
                      ->setMaxDepth(4)         
                      ->setPartial('partial/admin-breadcrumbs');
        ?>
    </div>
</div>

<div class="wrapper wrapper-content">
    <div class="row">
        <div class="col-lg-12">
            <div class="mail-box-header">
                <div class="pull-right tooltip-demo">
                    <a title="" data-placement="top" data-toggle="tooltip" class="btn btn-white btn-sm" href="<?php echo $this->url('admin/feedback', array('locale' => $this->currentLocale(), 'controller' => 'admin', 'action' => 'reply', 'id' => $this->feedback->id)); ?>" data-original-title="<?php echo $this->escapeHtmlAttr('Reply') ?>"><i class="fa fa-reply"></i> <?php echo $this->translate('Reply') ?></a>
                    <a title="" data-placement="top" data-toggle="tooltip" class="btn btn-white btn-sm" href="#" data-original-title="<?php echo $this->escapeHtmlAttr($this->translate('Print')) ?>"><i class="fa fa-print"></i> </a>
                    <a title="<?php echo $this->escapeHtmlAttr($this->translate('Move to trash')) ?>" data-placement="top" data-toggle="tooltip" class="btn btn-white btn-sm" href="<?php echo $this->url('admin/feedback', array('locale' => $this->currentLocale(), 'controller' => 'admin', 'action' => 'delete', 'id' => $this->feedback->id)); ?>"><i class="fa fa-trash-o"></i> </a>
                </div>
                <h2><?php echo $this->translate('View feedback') ?></h2>
                <div class="mail-tools tooltip-demo m-t-md">
                    <h3>
                        <span class="font-noraml"><?php echo $this->translate('Subject') ?>: </span>
                        <span><?php echo ucfirst($this->feedback->subject) ?></span>
                    </h3>
                    <h5>
                        <span class="pull-right font-noraml">
                            <?php  
                                echo $this->dateFormat(
                                    (int) $this->feedback->time,
                                    IntlDateFormatter::LONG, // date
                                    IntlDateFormatter::SHORT, // time
                                    $this->currentLocale() != 'uz-UZ' ? $this->currentLocale() : 'uz-Latn-UZ'
                                );
                            ?>
                        </span>
                        <span class="font-noraml"><?php echo $this->translate('From') ?>: </span>
                        <span><?php echo $this->feedback->email ?></span>
                    </h5>
                </div>
            </div>
            <div class="mail-box">
                <div class="mail-body">
                    <?php echo str_replace(array("\t", "\r\n"), array("&nbsp;&nbsp;", "<br>"), $this->feedback->text) ?>
                </div>
                <div class="mail-body">
                    <a href="<?php echo $this->url('admin/feedback', array('locale' => $this->currentLocale())) ?>" class="btn btn-sm btn-white" style="vertical-align: middle;">
                        <i class="fa fa-arrow-left fa-fw"></i>
                        <span><?php echo $this->translate('Back') ?></span>
                    </a>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>
</div>