<?php echo $this->doctype(); ?>
<html lang="<?php echo substr($this->currentLocale(), 0, 2) ?>">
<head>
    <meta charset="utf-8">
    <base href="<?php echo $this->basePath('/') ?>">
    <?php
        echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge');
        echo $this->headTitle($this->translate('Enter site'));
    ?>

    <?php
        echo $this->headLink(
            array(
                'rel' => 'shortcut icon',
                'type' => 'image/vnd.microsoft.icon',
                'href' => $this->basePath('img/favicon.ico')
            )
        )
        ->appendStylesheet($this->basePath('dist/plugins/bootstrap/css/bootstrap.min.css'))
        ->appendStylesheet($this->basePath('dist/plugins/font-awesome/css/font-awesome.css'))
        ->appendStylesheet($this->basePath('dist/css/animate.css'))
        ->appendStylesheet($this->basePath('dist/css/admin.css'));
    ?>

    <?php echo $this->headStyle() ?>

    <?php 
        echo $this->headScript()
            ->appendFile($this->basePath('dist/js/jquery-2.1.1.js'));
    ?>
</head>
<body class="gray-bg">
    <?php echo $this->content; ?>
    
    <?php
        echo $this->inlineScript()
            ->appendFile($this->basePath('dist/plugins/bootstrap/js/bootstrap.min.js'));
    ?>
</body>
</html>
