<?php
    echo $this->headTitle()->append($this->translate('Menu manager'));
    echo $this->headLink()
        ->appendStylesheet($this->basePath('dist/plugins/dataTables/dataTables.bootstrap.css'))
        ->appendStylesheet($this->basePath('dist/plugins/dataTables/dataTables.responsive.css'))
        ->appendStylesheet($this->basePath('dist/plugins/dataTables/dataTables.tableTools.min.css'))
        ->appendStylesheet($this->basePath('dist/plugins/dataTables/dataTables.custom.css'));
?>

<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-sm-8">
        <h2><?php echo $this->translate('Menu manager') ?></h2>

        <?php
            echo $this->navigation('Zend\Navigation\Admin')
                ->breadcrumbs()
                ->setMinDepth(0)
                ->setMaxDepth(4)
                ->setPartial('partial/admin-breadcrumbs');
        ?>
    </div>

    <div class="col-sm-4">
        <div class="title-action">
            <a href="<?php
                echo $this->url(
                    'admin/menu',
                    array(
                        'locale' => $this->currentLocale(),
                        'action' => 'add'
                    )
                );
            ?>" class="btn btn-primary">
                <?php echo $this->translate('Add new menu'); ?>
            </a>
        </div>
    </div>
</div>

<div class="wrapper wrapper-content">
    <?php if($this->menus): ?>
        <div class="row">  
            <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5><?php echo $this->translate('Menu') ?></h5>
                        <div class="ibox-tools">
                            <a class="collapse-link">
                                <i class="fa fa-chevron-down"></i>
                            </a>
                        </div>
                    </div>
                    <div class="ibox-content table-responsive">
                        <table class="table datatable">
                            <thead>
                                <th>#</th>
                                <th><?php echo $this->translate('Name') ?></th>
                                <th><?php echo $this->translate('Language') ?></th>
                                <th><?php echo $this->translate('Position') ?></th>
                                <th></th>
                            </thead>
                            <tbody>
                                <?php $order = 1; foreach($this->menus as $menu): ?>
                                    <tr>
                                        <td><?php echo $order ?></td>
                                        <td><?php echo $menu->name ?></td>
                                        <td><?php echo isset($this->locales[$menu->locale])? $this->locales[$menu->locale] : '' ?></td>
                                        <td>
                                            <span class="label label-info"><?php echo isset($positions[$menu->position])? $positions[$menu->position]: '-' ?></span>
                                        </td>
                                        <td>
                                            <a class="btn btn-default btn-rounded btn-outline" data-toggle="tooltip" data-placement="top" data-original-title="<?php echo $this->escapeHtmlAttr($this->translate('Edit')) ?>" href="<?php echo $this->url('admin/menu', array('locale' => $this->currentLocale(), 'action' => 'edit', 'menu' => $menu->id)) ?>">
                                                <i class="fa fa-edit"></i>
                                            </a>
                                            <a class="btn btn-default btn-rounded btn-outline" data-toggle="tooltip" data-placement="top" data-original-title="<?php echo $this->escapeHtmlAttr($this->translate('Delete')) ?>" href="<?php echo $this->url('admin/menu', array('locale' => $this->currentLocale(), 'action' => 'delete', 'menu' => $menu->id)) ?>">
                                                <i class="fa fa-trash"></i>
                                            </a>
                                        </td>
                                    </tr>
                                <?php $order++; endforeach; ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    <?php else: ?>
        <div class="middle-box text-center alert alert-info">
            <h3 class="font-bold"><?php echo $this->translate('There are no menu to display') ?></h3>
            <div class="error-desc">
                <?php echo $this->translate('You can add new menu by clicking link below') ?>
                <br>
                <a class="btn btn-info m-t" href="<?php echo $this->url('admin/menu', array('locale' => $this->currentLocale(), 'action' => 'add')) ?>"><?php echo $this->translate('Add new menu') ?></a>
            </div>
        </div>
    <?php endif; ?>
</div>

<?php
    echo $this->inlineScript()
        ->appendFile($this->basePath('dist/plugins/dataTables/jquery.dataTables.js'))
        ->appendFile($this->basePath('dist/plugins/dataTables/dataTables.bootstrap.js'))
        ->appendFile($this->basePath('dist/plugins/dataTables/dataTables.responsive.js'))
        ->appendFile($this->basePath('dist/plugins/dataTables/dataTables.tableTools.min.js'))
        ->appendScript("
            $('.datatable').dataTable({
                'responsive': true,
                'language': {
                    'url': '".$this->url('application/default', array('locale' => $this->currentLocale(), 'controller' => 'jsPlugins', 'action' => 'datatablesI18n'))."'
                }
            });
            $('*[data-toggle=\"tooltip\"]').tooltip();
        ");
?>