<div id="wrapper-content"><!-- PAGE WRAPPER-->
    <div id="page-wrapper"><!-- MAIN CONTENT-->
        <div class="main-content"><!-- CONTENT-->
            <div class="content">
                <div class="section background-opacity page-title set-height-top">
                    <div class="container">
                        <div class="page-title-wrapper"><h2 class="captions">news & update</h2>
                            <ol class="breadcrumb">
                                <li><a href="index.html">Home</a></li>
                                <li class="active"><a href="#">News</a></li>
                            </ol>
                        </div>
                    </div>
                </div>
                <div class="section nav-subscribe">
                    <div class="container">
                        <div class="nav-subscribe-wrapper">
                            <div class="nav-subscribe-left"><p class="subscribe-text">Subscribe <b class="focus">Edugate</b> to learn new creative skill</p></div>
                            <div class="nav-subscribe-right">
                                <button class="btn btn-green btn-bold"><span>SUBSCRIBE NOW</span></button>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="section section-padding news-page">
                    <div class="container">
                        <div class="row">
                            <div class="col-md-9">
                                <div class="news-page-wrapper">
                                    <div class="edugate-layout-1">
                                        <div class="edugate-image"><img src="assets/images/news/news-1.jpg" alt="" class="img-responsive"/></div>
                                        <div class="edugate-content"><a href="news-detail.html" class="title">E-Learn 2015 - World Conference on Edugate Website</a>

                                            <div class="info">
                                                <div class="author item"><a href="#">By Admin</a></div>
                                                <div class="date-time item"><a href="#">17 sep 2015</a></div>
                                            </div>
                                            <div class="info-more">
                                                <div class="view item"><i class="fa fa-user"></i>

                                                    <p> 56</p></div>
                                                <div class="comment item"><i class="fa fa-comment"></i>

                                                    <p> 239</p></div>
                                            </div>
                                            <div class="description">Dalmatian hello amazing the rmore flung as thanks a manta dealt to under emu some the and one baldbe dear sobbingly save and spitefully less.</div>
                                            <button class="btn btn-green"><span>read more</span></button>
                                        </div>
                                    </div>
                                    <div class="edugate-layout-1">
                                        <div class="edugate-image"><img src="assets/images/news/news-2.jpg" alt="" class="img-responsive"/></div>
                                        <div class="edugate-content"><a href="news-detail.html" class="title">E-Learn 2015 - World Conference on Edugate Website</a>

                                            <div class="info">
                                                <div class="author item"><a href="#">By Admin</a></div>
                                                <div class="date-time item"><a href="#">17 sep 2015</a></div>
                                            </div>
                                            <div class="info-more">
                                                <div class="view item"><i class="fa fa-user"></i>

                                                    <p> 56</p></div>
                                                <div class="comment item"><i class="fa fa-comment"></i>

                                                    <p> 239</p></div>
                                            </div>
                                            <div class="description">Dalmatian hello amazing the rmore flung as thanks a manta dealt to under emu some the and one baldbe dear sobbingly save and spitefully less.</div>
                                            <button class="btn btn-green"><span>read more</span></button>
                                        </div>
                                    </div>
                                    <div class="edugate-layout-1">
                                        <div class="edugate-image"><img src="assets/images/news/news-3.jpg" alt="" class="img-responsive"/></div>
                                        <div class="edugate-content"><a href="news-detail.html" class="title">E-Learn 2015 - World Conference on Edugate Website</a>

                                            <div class="info">
                                                <div class="author item"><a href="#">By Admin</a></div>
                                                <div class="date-time item"><a href="#">17 sep 2015</a></div>
                                            </div>
                                            <div class="info-more">
                                                <div class="view item"><i class="fa fa-user"></i>

                                                    <p> 56</p></div>
                                                <div class="comment item"><i class="fa fa-comment"></i>

                                                    <p> 239</p></div>
                                            </div>
                                            <div class="description">Dalmatian hello amazing the rmore flung as thanks a manta dealt to under emu some the and one baldbe dear sobbingly save and spitefully less.</div>
                                            <button class="btn btn-green"><span>read more</span></button>
                                        </div>
                                    </div>
                                    <div class="edugate-layout-1">
                                        <div class="edugate-image"><img src="assets/images/news/news-4.jpg" alt="" class="img-responsive"/></div>
                                        <div class="edugate-content"><a href="news-detail.html" class="title">E-Learn 2015 - World Conference on Edugate Website</a>

                                            <div class="info">
                                                <div class="author item"><a href="#">By Admin</a></div>
                                                <div class="date-time item"><a href="#">17 sep 2015</a></div>
                                            </div>
                                            <div class="info-more">
                                                <div class="view item"><i class="fa fa-user"></i>

                                                    <p> 56</p></div>
                                                <div class="comment item"><i class="fa fa-comment"></i>

                                                    <p> 239</p></div>
                                            </div>
                                            <div class="description">Dalmatian hello amazing the rmore flung as thanks a manta dealt to under emu some the and one baldbe dear sobbingly save and spitefully less.</div>
                                            <button class="btn btn-green"><span>read more</span></button>
                                        </div>
                                    </div>
                                    <div class="edugate-layout-1">
                                        <div class="edugate-image"><img src="assets/images/news/news-5.jpg" alt="" class="img-responsive"/></div>
                                        <div class="edugate-content"><a href="news-detail.html" class="title">E-Learn 2015 - World Conference on Edugate Website</a>

                                            <div class="info">
                                                <div class="author item"><a href="#">By Admin</a></div>
                                                <div class="date-time item"><a href="#">17 sep 2015</a></div>
                                            </div>
                                            <div class="info-more">
                                                <div class="view item"><i class="fa fa-user"></i>

                                                    <p> 56</p></div>
                                                <div class="comment item"><i class="fa fa-comment"></i>

                                                    <p> 239</p></div>
                                            </div>
                                            <div class="description">Dalmatian hello amazing the rmore flung as thanks a manta dealt to under emu some the and one baldbe dear sobbingly save and spitefully less.</div>
                                            <button class="btn btn-green"><span>read more</span></button>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <nav class="pagination col-md-12">
                                        <ul class="pagination__list">
                                            <li><a rel="prev" href="#" class="pagination__previous btn-squae disable">&#8249;</a></li>
                                            <li><span class="pagination__page btn-squae active">1</span></li>
                                            <li><a href="#" class="pagination__page btn-squae">2</a></li>
                                            <li><a href="#" class="pagination__page btn-squae">...</a></li>
                                            <li><a href="#" class="pagination__page btn-squae">14</a></li>
                                            <li><a rel="next" href="#" class="pagination__next btn-squae">&#8250;</a></li>
                                        </ul>
                                    </nav>
                                </div>
                            </div>
                            <div class="col-md-3 sidebar layout-right">
                                <div class="row">
                                    <div class="recent-post-widget widget col-sm-6 col-md-12 col-xs-6 sd380">
                                        <div class="title-widget">recent post</div>
                                        <div class="content-widget">
                                            <div class="media">
                                                <div class="media-left"><a href="courses-detail.html" class="link"><img src="assets/images/recent-post/recent-post-1.jpg" alt="" class="media-image"/></a></div>
                                                <div class="media-right">
                                                    <div class="info">
                                                        <div class="date-created item"><a href="#"><span>Aug 18, 2015</span></a></div>
                                                    </div>
                                                    <a href="courses-detail.html" class="link comment"><i class="fa fa-comment"></i><span>3</span></a><a href="courses-detail.html" class="link title">Build a Microblogging App With Flux and React</a></div>
                                            </div>
                                            <div class="media">
                                                <div class="media-left"><a href="courses-detail.html" class="link"><img src="assets/images/recent-post/recent-post-2.jpg" alt="" class="media-image"/></a></div>
                                                <div class="media-right">
                                                    <div class="info">
                                                        <div class="date-created item"><a href="#"><span>Aug 18, 2015</span></a></div>
                                                    </div>
                                                    <a href="courses-detail.html" class="link comment"><i class="fa fa-comment"></i><span>3</span></a><a href="courses-detail.html" class="link title">Build a Microblogging App With Flux and React</a></div>
                                            </div>
                                            <div class="media">
                                                <div class="media-left"><a href="courses-detail.html" class="link"><img src="assets/images/recent-post/recent-post-3.jpg" alt="" class="media-image"/></a></div>
                                                <div class="media-right">
                                                    <div class="info">
                                                        <div class="date-created item"><a href="#"><span>Aug 18, 2015</span></a></div>
                                                    </div>
                                                    <a href="courses-detail.html" class="link comment"><i class="fa fa-comment"></i><span>3</span></a><a href="courses-detail.html" class="link title">Build a Microblogging App With Flux and React</a></div>
                                            </div>
                                            <div class="media">
                                                <div class="media-left"><a href="courses-detail.html" class="link"><img src="assets/images/recent-post/recent-post-4.jpg" alt="" class="media-image"/></a></div>
                                                <div class="media-right">
                                                    <div class="info">
                                                        <div class="date-created item"><a href="#"><span>Aug 18, 2015</span></a></div>
                                                    </div>
                                                    <a href="courses-detail.html" class="link comment"><i class="fa fa-comment"></i><span>3</span></a><a href="courses-detail.html" class="link title">Build a Microblogging App With Flux and React</a></div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="popular-course-widget widget col-sm-6 col-md-12 col-xs-6 sd380">
                                        <div class="title-widget">popular courses</div>
                                        <div class="content-widget">
                                            <div class="media">
                                                <div class="media-left"><a href="courses-detail.html" class="link"><img src="assets/images/popular/popular-1.jpg" alt="" class="media-image"/></a></div>
                                                <div class="media-right">
                                                    <div class="cur">35</div>
                                                    <a href="courses-detail.html" class="link title">Adobe Lightroom CC for Photographers</a>

                                                    <div class="info">
                                                        <div class="author item"><a href="#"><span>By Sandara</span></a></div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="media">
                                                <div class="media-left"><a href="courses-detail.html" class="link"><img src="assets/images/popular/popular-2.jpg" alt="" class="media-image"/></a></div>
                                                <div class="media-right">
                                                    <div class="cur">40</div>
                                                    <a href="courses-detail.html" class="link title">Adobe Lightroom CC for Photographers</a>

                                                    <div class="info">
                                                        <div class="author item"><a href="#"><span>By Sandara</span></a></div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="media">
                                                <div class="media-left"><a href="courses-detail.html" class="link"><img src="assets/images/popular/popular-3.jpg" alt="" class="media-image"/></a></div>
                                                <div class="media-right">
                                                    <div class="cur">34</div>
                                                    <a href="courses-detail.html" class="link title">Adobe Lightroom CC for Photographers</a>

                                                    <div class="info">
                                                        <div class="author item"><a href="#"><span>By Sandara</span></a></div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="media">
                                                <div class="media-left"><a href="courses-detail.html" class="link"><img src="assets/images/popular/popular-4.jpg" alt="" class="media-image"/></a></div>
                                                <div class="media-right">
                                                    <div class="cur">27</div>
                                                    <a href="courses-detail.html" class="link title">Adobe Lightroom CC for Photographers</a>

                                                    <div class="info">
                                                        <div class="author item"><a href="#"><span>By Sandara</span></a></div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="clearfix"></div>
                                    <div class="category-widget widget col-sm-6 col-md-12 col-xs-6 sd380">
                                        <div class="title-widget">categories</div>
                                        <div class="content-widget">
                                            <ul class="category-widget list-unstyled">
                                                <li><a href="categories.html" class="link cat-item"><span class="pull-left">Web Design</span><span class="pull-right">125</span></a></li>
                                                <li><a href="categories.html" class="link cat-item"><span class="pull-left">Wordpress Themes</span><span class="pull-right">97</span></a></li>
                                                <li><a href="categories.html" class="link cat-item"><span class="pull-left">Photography</span><span class="pull-right">56</span></a></li>
                                                <li><a href="categories.html" class="link cat-item"><span class="pull-left">Video</span><span class="pull-right">24</span></a></li>
                                                <li><a href="categories.html" class="link cat-item"><span class="pull-left">Miscellaneous</span><span class="pull-right">13</span></a></li>
                                            </ul>
                                        </div>
                                    </div>
                                    <div class="tag-widget widget col-sm-6 col-md-12 col-xs-6 sd380">
                                        <div class="title-widget">tags</div>
                                        <div class="content-widget">
                                            <ul class="tag-widget list-unstyled">
                                                <li><a href="#" class="tag-item">Software</a></li>
                                                <li><a href="#" class="tag-item">Music</a></li>
                                                <li><a href="#" class="tag-item">Photography</a></li>
                                                <li><a href="#" class="tag-item">Communication</a></li>
                                                <li><a href="#" class="tag-item">Tutorial</a></li>
                                                <li><a href="#" class="tag-item">Biology</a></li>
                                                <li><a href="#" class="tag-item">Photoshop</a></li>
                                                <li><a href="#" class="tag-item">Economics</a></li>
                                                <li><a href="#" class="tag-item">Statistics</a></li>
                                            </ul>
                                        </div>
                                    </div>
                                    <div class="clearfix"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- BUTTON BACK TO TOP-->
    <div id="back-top"><a href="#top"><i class="fa fa-angle-double-up"></i></a></div>
</div>