<?php echo $this->headTitle()->append($this->translate('Delete category')) ?>
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-sm-8">
        <h2><?php echo $this->translate('Delete category') ?></h2>
        <?php
            $this->plugin('navigation')->setContainer($this->navigation('Zend\Navigation\Admin')->getContainer());

            echo $this->navigation()
                      ->breadcrumbs() 
                      ->setMinDepth(0)              
                      ->setMaxDepth(4)         
                      ->setPartial('partial/admin-breadcrumbs');
        ?>
    </div>
</div>
<div class="wrapper wrapper-content">
    <div class="middle-box text-center alert alert-danger">
        <h3 class="font-bold"><?php echo $this->translate('Are you sure?') ?></h3>
        <div class="error-desc">
            <?php echo sprintf($this->translate('Category: \'%s\' will be deleted. This operation can not be prevented!'), $this->category->title) ?>
            <br>
            <a class="btn btn-danger m-t" href="<?php echo $this->url('admin/categories', array('locale' => $this->currentLocale(), 'action' => 'delete', 'category' => $this->category->id), array('query' => array('confirm' => true))) ?>"><?php echo $this->translate('Delete') ?></a>
        	<a class="btn btn-primary m-t" href="<?php echo $this->url('admin/categories', array('locale' => $this->currentLocale())) ?>"><?php echo $this->translate('Cancel') ?></a>
        </div>
    </div>
</div>