<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 */
$this->headTitle()->append(sprintf(
    '%s :: %s',
    $this->translate('Edit category'),
    $this->translate('Categories')
));

/**
 * @var \Admin\Form\Categories $form
 */
$form = $this->get('form');

$form->setAttribute(
    'action',
    $this->url(
        'admin/categories',
        [
            'locale' => $this->currentLocale(),
            'action' => 'edit',
            'category' => $this->category->id
        ]
    )
);
$form->prepare();

$formLabel = $this->plugin('formLabel');
?>

<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-sm-8">
        <h2><?php echo $this->translate('Edit category') ?></h2>
        <?php
            $this->plugin('navigation')->setContainer(
                $this->navigation('Zend\Navigation\Admin')->getContainer()
            );

            echo $this->navigation()
            ->breadcrumbs()
            ->setMinDepth(0)
            ->setMaxDepth(4)
            ->setPartial('partial/admin-breadcrumbs');
        ?>
    </div>
</div>

<div class="wrapper wrapper-content">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5><?php echo $this->translate('Category properties') ?></h5>
                </div>

                <div class="ibox-content">
                    <?php echo $this->form()->openTag($form) ?>
                        <?php if($this->errors): ?>
                            <div class="alert alert-danger">
                                <?php foreach($this->errors as $error): ?>
                                    <b><?php echo $this->translate($error) ?></b>
                                <?php endforeach; ?>
                            </div>
                        <?php endif; ?>

                        <div class="form-group<?php if($form->get('title')->getMessages()) echo ' has-error' ?>">
                            <?php
                                echo $formLabel->openTag();
                                echo $this->translate($form->get('title')->getOption('label'));
                                echo '<span style="color:red;">*</span>';
                                echo $formLabel->closeTag();
                                echo $this->formText($form->get('title')->setAttribute('class', 'form-control'));
                                echo $this->formElementErrors($form->get('title'));
                            ?>
                        </div>

                        <div class="clearfix"></div>
                        <button type="submit" class="btn btn-success">
                            <span><?php echo $this->translate('Save') ?></span>
                        </button>
                        <a href="<?php echo $this->url('admin/categories', array('locale' => $this->currentLocale())) ?>" class="btn btn-warning">
                            <span><?php echo $this->translate('Cancel') ?></span>
                        </a>
                    <?php echo $this->form()->closeTag() ?>
                </div>
            </div>
        </div>
    </div>
</div>
