<?php echo $this->headTitle()->append($this->translate('Add video'))->append($this->translate('Media')) ?>
<?php $this->form->prepare(); ?>
<div class="row wrapper border-bottom white-bg page-heading">
	<div class="col-sm-8">
		<h2><?php echo $this->translate('Add video') ?></h2>
		<?php
            $this->plugin('navigation')->setContainer($this->navigation('Zend\Navigation\Admin')->getContainer());

            echo $this->navigation()
                      ->breadcrumbs()
                      ->setMinDepth(0)               
                      ->setMaxDepth(4)         
                      ->setPartial('partial/admin-breadcrumbs');
        ?>
	</div>
	<div class="col-sm-4">
		<div class="title-action">
            <a class="btn btn-primary" href="<?php echo $this->url('admin/media', array('locale' => $this->currentLocale(), 'action' => 'videos')) ?>">
            	<i class="fa fa-arrow-left"></i>
            	<?php echo $this->translate('Back'); ?>
            </a>
        </div>
	</div>
</div>
<div class="wrapper wrapper-content">
	<div class="row">
		<div class="col-lg-12">
			<div class="ibox float-e-margins">
				<div class="ibox-title">
					<h5><?php echo $this->translate('Add video'); ?></h5>
					<div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-down"></i>
                        </a>
                    </div>
				</div>
				<div class="ibox-content">
					<?php echo $this->form()->openTag($this->form); ?>
						<div class="form-group">
							<?php echo $this->formLabel($this->form->get('src')); ?>
							<?php echo $this->formTextarea($this->form->get('src')); ?>
							<?php echo $this->formElementErrors($this->form->get('src')); ?>
						</div>
						<div class="preview-container" style="display: none;">
							<h4><?php echo $this->translate('Preview'); ?></h4>
							<div class="preview" style="margin-bottom: 25px;"></div>
						</div>
						<div class="form-group">
							<button type="submit" class="btn btn-primary">
								<i class="fa fa-save"></i>
								<?php echo $this->translate('Add'); ?>
							</button>
							<a href="<?php echo $this->url('admin/media', array('locale' => $this->currentLocale(), 'action' => 'videos')); ?>" class="btn btn-danger">
								<i class="fa fa-remove"></i>
								<?php echo $this->translate('Cancel'); ?>
							</a>
							<button type="button" id="previewBtn" class="btn btn-info">
								<i class="fa fa-play-circle"></i>
								<?php echo $this->translate('Preview'); ?>
							</button>
						</div>
					<?php echo $this->form()->closeTag(); ?>
				</div>
			</div>
		</div>
	</div>
</div>
<script>
	$('#previewBtn').click(function() {
		var html = $("textarea[name='src']").val();

		if (html != "") {
			$('.preview-container').slideUp('fast', function() {
				var preview = $(this).find('.preview');
				preview.empty().html(html);
				$(this).slideDown('fast');
			})
		}
	});
</script>