<?php
    echo $this->headTitle()
        ->append($this->translate('Add images collection'))
        ->append($this->translate('Media'));
    echo $this->headlink()
       ->appendStylesheet('dist/plugins/fine-uploader/fine-uploader-gallery.min.css');
?>
<?php $this->imgCollectionForm->setAttribute("action", "")->prepare(); ?>
<div class="row wrapper border-bottom white-bg page-heading">
	<div class="col-sm-8">
		<h2><?php echo $this->translate('Add images collection') ?></h2>
		<?php
            $this->plugin('navigation')->setContainer($this->navigation('Zend\Navigation\Admin')->getContainer());

            echo $this->navigation()
              ->breadcrumbs()
              ->setMinDepth(0)
              ->setMaxDepth(4)
              ->setPartial('partial/admin-breadcrumbs');
        ?>
	</div>

	<div class="col-sm-4">
        <div class="title-action">
    		<a href="<?php echo $this->url('admin/media',array('locale' => $this->currentLocale(), 'action' => 'collections')); ?>" class="btn btn-primary cancel-btn">
                <i class="fa fa-arrow-left"></i>
                <span><?php echo $this->translate('Back'); ?></span>
            </a>
        </div>
	</div>
</div>

<div class="wrapper wrapper-content">   
    <div class="row">
        <div class="col-md-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5><?php echo $this->translate('Add images collection'); ?></h5>
                </div>
                <div class="ibox-content">
                    <?php echo $this->form()->openTag($this->imgCollectionForm); ?>
                        <div class="form-group">
                            <?php echo $this->formLabel($this->imgCollectionForm->get('collection-name')); ?>
                            <div class="input-group">
                                <?php echo $this->formText($this->imgCollectionForm->get('collection-name')); ?>
                                <span class="input-group-btn">
                                    <button type="button" id="check-name" class="btn btn-success">
                                        <?php echo $this->translate('Check') ?>
                                        <i class="fa fa-check"></i>
                                    </button>
                                </span>
                            </div>
                        </div>
                        <div class="name-errors"></div>
                    <?php echo $this->form()->closeTag(); ?>
                    <div class="clearfix"></div>
                </div>
            </div>
        </div>
    </div>
	<div class="row">
		<div class="col-md-12">
			<div id="fine-uploader-gallery" style="display: none;"></div>
		</div>
	</div>
</div>

<script type="text/template" id="qq-template-gallery">
    <div class="qq-uploader-selector qq-uploader qq-gallery" qq-drop-area-text="Drop files here" style="background-color: white;">
        <div class="qq-total-progress-bar-container-selector qq-total-progress-bar-container">
            <div role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" class="qq-total-progress-bar-selector qq-progress-bar qq-total-progress-bar"></div>
        </div>
        <div class="qq-upload-drop-area-selector qq-upload-drop-area" qq-hide-dropzone>
            <span class="qq-upload-drop-area-text-selector"></span>
        </div>
        <div class="qq-upload-button-selector qq-upload-button">
            <div>Upload a file</div>
        </div>
        <span class="qq-drop-processing-selector qq-drop-processing">
            <span>Processing dropped files...</span>
            <span class="qq-drop-processing-spinner-selector qq-drop-processing-spinner"></span>
        </span>
        <ul class="qq-upload-list-selector qq-upload-list" role="region" aria-live="polite" aria-relevant="additions removals">
            <li>
                <span role="status" class="qq-upload-status-text-selector qq-upload-status-text"></span>
                <div class="qq-progress-bar-container-selector qq-progress-bar-container">
                    <div role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" class="qq-progress-bar-selector qq-progress-bar"></div>
                </div>
                <span class="qq-upload-spinner-selector qq-upload-spinner"></span>
                <div class="qq-thumbnail-wrapper">
                    <img class="qq-thumbnail-selector" qq-max-size="120" qq-server-scale>
                </div>
                <button type="button" class="qq-upload-cancel-selector qq-upload-cancel">X</button>
                <button type="button" class="qq-upload-retry-selector qq-upload-retry">
                    <span class="qq-btn qq-retry-icon" aria-label="Retry"></span>
                    Retry
                </button>

                <div class="qq-file-info">
                    <div class="qq-file-name">
                        <span class="qq-upload-file-selector qq-upload-file"></span>
                        <span class="qq-edit-filename-icon-selector qq-edit-filename-icon" aria-label="Edit filename"></span>
                    </div>
                    <input class="qq-edit-filename-selector qq-edit-filename" tabindex="0" type="text">
                    <span class="qq-upload-size-selector qq-upload-size"></span>
                    <button type="button" class="qq-btn qq-upload-delete-selector qq-upload-delete">
                        <span class="qq-btn qq-delete-icon" aria-label="Delete"></span>
                    </button>
                    <button type="button" class="qq-btn qq-upload-pause-selector qq-upload-pause">
                        <span class="qq-btn qq-pause-icon" aria-label="Pause"></span>
                    </button>
                    <button type="button" class="qq-btn qq-upload-continue-selector qq-upload-continue">
                        <span class="qq-btn qq-continue-icon" aria-label="Continue"></span>
                    </button>
                </div>
            </li>
        </ul>

        <dialog class="qq-alert-dialog-selector">
            <div class="qq-dialog-message-selector"></div>
            <div class="qq-dialog-buttons">
                <button type="button" class="qq-cancel-button-selector">Close</button>
            </div>
        </dialog>

        <dialog class="qq-confirm-dialog-selector">
            <div class="qq-dialog-message-selector"></div>
            <div class="qq-dialog-buttons">
                <button type="button" class="qq-cancel-button-selector">No</button>
                <button type="button" class="qq-ok-button-selector">Yes</button>
            </div>
        </dialog>

        <dialog class="qq-prompt-dialog-selector">
            <div class="qq-dialog-message-selector"></div>
            <input type="text">
            <div class="qq-dialog-buttons">
                <button type="button" class="qq-cancel-button-selector">Cancel</button>
                <button type="button" class="qq-ok-button-selector">Ok</button>
            </div>
        </dialog>
    </div>
</script>
<?php 
	

	echo $this->headScript()
	   ->appendFile($this->basePath('dist/plugins/fine-uploader/fine-uploader.min.js'));

	echo $this->inlineScript()
    	->appendScript("	
    		var galleryUploader = new qq.FineUploader({
                element: document.getElementById(\"fine-uploader-gallery\"),
                template: 'qq-template-gallery',
                request: {
                    endpoint: '".$this->url('admin/media', array('locale' => $this->currentLocale(), 'action' => 'upload'))."'
                },
                thumbnails: {
                    placeholders: {
                        waitingPath: 'img/fine-uploader/placeholders/waiting-generic.png',
                        notAvailablePath: 'img/fine-uploader/placeholders/not_available-generic.png'
                    }
                },
                validation: {
                    allowedExtensions: ['jpeg', 'jpg', 'gif', 'png']
                },
                callbacks: {
                    onComplete: function(id, name, response, xhr) {
                        var button = $('.cancel-btn');
                        button.children('span').text('" . $this->escapeHtmlAttr($this->translate('Done')) . "');
                        button.children('.fa').removeClass('fa-arrow-left').addClass('fa-check');
                    }
                }
            });
    	");
?>
<script>
    $('#check-name').closest('form').submit(function(e) {
        e.preventDefault();
        return false;
    });

    $('#check-name').click(function() {
        var $this = $(this);
        var nameInput = $('#collection-name');
    
        $.ajax({
            url: "<?php echo $this->url('admin/default', array('locale' => $this->currentLocale(), 'controller' => 'media', 'action' => 'checkCollectionName')); ?>",
            type: 'post',
            data: { 'collection-name' : nameInput.val() },
            success: function(data, status, xhr) {
                
                if (data.status == "success") {
                    $this.closest('.col-md-12').slideUp('normal', function() {
                        $(this).empty().append("<h2>" + nameInput.val() + "</h2>").slideDown();
                    });

                    $('#fine-uploader-gallery').slideDown();
                }
                else {
                    $('.name-errors').empty().append(
                        '<div class="alert alert-danger alert-dismissable fade in" role="alert">' +
                            '<button type="button" class="close" data-dismiss="alert" aria-label="Close">' +
                                '<span aria-hidden="true">&times;</span>' +
                            '</button> ' +
                            data.error +
                        '</div>'
                    );   
                }
            },
            error: function(xhr, status, error) {
                $('.name-errors').empty().append(
                    '<div class="alert alert-danger alert-dismissable fade in" role="alert">' +
                        '<button type="button" class="close" data-dismiss="alert" aria-label="Close">' +
                            '<span aria-hidden="true">&times;</span>' +
                        '</button> ' +
                        error +
                    '</div>'
                );
            }
        });
    });
</script>