<?php echo $this->headTitle()->append($this->translate('Edit images collection'))->append($this->translate('Media')) ?>
<?php $mediaConfig = $this->getHelperPluginManager()->getServiceLocator()->get('config')['media']; ?>
<div class="row wrapper border-bottom white-bg page-heading">
	<div class="col-sm-10">
		<h2><?php echo $this->translate('Edit images collection') ?></h2>
		<?php
			$this->plugin('navigation')->setContainer($this->navigation('Zend\Navigation\Admin')->getContainer());

			echo $this->navigation()
					  ->breadcrumbs()
					  ->setMinDepth(0)               
					  ->setMaxDepth(4)         
					  ->setPartial('partial/admin-breadcrumbs');
		?>
	</div>
	<div class="col-sm-2">
		
	</div>
</div>
<div class="wrapper wrapper-content">  
	<div class="row">
		<div class="col-xs-12">
			<div class="ibox float-e-margins">
				<div class="ibox-title">
					<h5><?php echo $this->translate("Delete collection's image"); ?></h5>
				</div>
				<div class="ibox-content">
					<?php $src = $mediaConfig['public_path'] . "collection_" . $this->collection->name . "/" .$this->collection->src; ?>
					<img src="<?php echo $this->basePath($src); ?>" class="img-responsive img-thumbnail">
					<br><br>
					<h3><?php echo $this->translate('Do you want to delete this image file ?'); ?></h3>
					<form action="" method="post">
						<div class="form-group">
							<button class="btn-danger btn">
								<i class="fa fa-trash"></i>
								<?php echo $this->translate('Delete'); ?>
							</button>
							<a class="btn-default btn" href="<?php echo $this->url('admin/media', array('locale' => $this->currentLocale(), 'action' => 'editImageCollection', 'collection' => $this->collection->name)); ?>">
								<i class="fa fa-remove"></i>
								<?php echo $this->translate('Cancel'); ?>
							</a>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>