<?php echo $this->headTitle()->append($this->translate('Edit video'))->append($this->translate('Media')) ?>
<div class="row wrapper border-bottom white-bg page-heading">
	<div class="col-sm-8">
		<h2><?php echo $this->translate('Edit video') ?></h2>
		<?php
            $this->plugin('navigation')->setContainer($this->navigation('Zend\Navigation\Admin')->getContainer());

            echo $this->navigation()
                      ->breadcrumbs()
                      ->setMinDepth(0)               
                      ->setMaxDepth(4)         
                      ->setPartial('partial/admin-breadcrumbs');
        ?>
	</div>
	<div class="col-sm-4">
		<div class="title-action">
            <a class="btn btn-primary" href="<?php echo $this->url('admin/media', array('locale' => $this->currentLocale(), 'action' => 'videos')) ?>">
            	<i class="fa fa-check"></i>
            	<?php echo $this->translate('Done'); ?>
            </a>
        </div>
	</div>
</div>
<div class="wrapper wrapper-content">
	<div class="row">
		<div class="col-lg-12">
			<div class="ibox float-e-margins">
				<div class="ibox-title">
					<h5><?php echo $this->translate('Edit video'); ?></h5>
					<div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-down"></i>
                        </a>
                    </div>
				</div>
				<div class="ibox-content">
					<h4><?php echo $this->translate('Video'); ?></h4>	
					<div class="preview" style="margin-bottom: 25px;">
						<?php echo $this->video->src; ?>
					</div>
					<?php if (count($this->descriptions) > 0) : ?>
					<h2><?php echo $this->translate('Descriptions to video'); ?></h2>
					<?php foreach ($this->descriptions as $desc) : ?>
					<div class="row">
						<div class="col-xs-10">
							<h4><?php echo $desc->locale; ?></h4>
							<p><?php echo $desc->text; ?></p>
						</div>
						<div class="col-xs-2">
							<a href="<?php echo $this->url('admin/media', array('locale' => $this->currentLocale(), 'action' => 'deleteVideoDescription', 'collection' => $this->video->id, 'id' => $desc->id)); ?>" class="btn btn-danger delete-desc-btn">
								<i class="fa fa-trash"></i>
								<span class="hidden-sm hidden-xs">
									<?php echo $this->translate('Delete'); ?>
								</span>
							</a>
						</div>
					</div>
					<div class="clearfix"></div><br><br>
					<?php endforeach; ?>
					<?php endif; ?>
					<?php if (count($this->locales) > 0) : ?>
					<?php $this->form->prepare(); ?>
					<h2><?php echo $this->translate('Add description'); ?></h2>
					<?php echo $this->form()->openTag($this->form); ?>
						<div class="form-group">
							<?php echo $this->formLabel($this->form->get('locale')); ?>
							<?php echo $this->formSelect($this->form->get('locale')); ?>
							<?php echo $this->formelementErrors($this->form->get('locale')); ?>
						</div>
						<div class="form-group">
							<?php echo $this->formLabel($this->form->get('text')); ?>
							<?php echo $this->formtextarea($this->form->get('text')); ?>
							<?php echo $this->formelementErrors($this->form->get('text')); ?>
						</div>
						<div class="form-group">
							<button type="submit" class="btn btn-primary">
								<i class="fa fa-save"></i>
								<?php echo $this->translate('Add'); ?>
							</button>
							<a href="<?php echo $this->url('admin/media', array('locale' => $this->currentLocale(), 'action' => 'videos')) ?>" class="btn btn-danger">
								<i class="fa fa-remove"></i>
								<?php echo $this->translate('Cancel'); ?>
							</a>
						</div>
					<?php echo $this->form()->closeTag(); ?>
					<?php endif; ?>
				</div>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
	$('.delete-desc-btn').click(function() {
		if ( ! confirm("<?php echo $this->translate('Do you want to delete this description ?'); ?>"))
			return false;
	});
</script>