<?php  
	$this->headTitle()->append($this->translate('Add'))->append($this->translate('Answers'))->append($this->translate('Quiz'));
?>
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-sm-8">
        <h2><?php echo $this->translate('Add new answer') ?></h2>
        <?php
            $this->plugin('navigation')->setContainer($this->navigation('Zend\Navigation\Admin')->getContainer());

            echo $this->navigation()
                      ->breadcrumbs()
                      ->setMinDepth(0)               
                      ->setMaxDepth(4)         
                      ->setPartial('partial/admin-breadcrumbs');
        ?>
    </div>
</div>
<div class="wrapper wrapper-content">
	<div class="row">
		<div class="col-lg-12">
			<div class="ibox float-e-margins">
				<div class="ibox-title">
					<h5><?php echo $this->translate('Answer') ?></h5>
				</div>
				<div class="ibox-content">
					<?php 
						$this->form
						->setAttribute(
							'action', 
							$this->url(
								'admin/quiz', 
								array(
									'locale' => $this->currentLocale(),
									'action' => 'addAnswer',
									'id'	 => $this->question->id,
								)
							)
						)
						->prepare();

						echo $this->form()->openTag($this->form);
					?>
						<div class="form-group">
							<?php echo $this->formLabel($this->form->get('text')) ?>
							<?php  
								echo $this->formTextarea
								(
									$this->form->get('text')
									->setAttribute('class', 'form-control')
								)
							?>
							<?php echo $this->formElementErrors($this->form->get('text')) ?>
						</div>
						<div class="form-group">
							<?php echo $this->formLabel($this->form->get('index')) ?>
							<?php  
								echo $this->formSelect
								(
									$this->form->get('index')
									->setAttribute('class', 'form-control')
								)
							?>
							<?php echo $this->formElementErrors($this->form->get('index')) ?>
						</div>
						<div>
							<button type="submit" class="btn btn-white">
								<i class="fa fa-fw fa-check"></i>
								<span><?php echo $this->translate('Save') ?></span>
							</button>
							<a href="<?php echo $this->url('admin/quiz', array('locale' => $this->currentLocale(), 'action' => 'edit', 'id' => $this->question->id)) ?>" class="btn btn-white">
								<i class="fa fa-fw fa-times"></i>
								<span><?php echo $this->translate('Cancel') ?></span>
							</a>
						</div>
					<?php echo $this->form()->closeTag() ?>
				</div>
			</div>
		</div>
	</div>
</div>