<?php  
    $this->headTitle()->append($this->translate('Delete'))->append($this->translate('Quiz'));
?>
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-sm-8">
        <h2><?php echo $this->translate('Delete question') ?></h2>
        <?php
            $this->plugin('navigation')->setContainer($this->navigation('Zend\Navigation\Admin')->getContainer());

            echo $this->navigation()
                      ->breadcrumbs() 
                      ->setMinDepth(0)              
                      ->setMaxDepth(4)         
                      ->setPartial('partial/admin-breadcrumbs');
        ?>
    </div>
</div>
<div class="wrapper wrapper-content">
    <div class="middle-box text-center alert alert-danger">
        <h3 class="font-bold"><?php echo $this->translate('Are you sure?') ?></h3>
        <div class="error-desc">
            <div class="well text-left">
                <h4><?php echo $this->question->text ?></h4>

                <?php if($answers = $this->question->getAnswers()): ?>
                    <h5><?php echo $this->translate('Answers') ?>:</h5>

                    <?php foreach($answers as $answer): ?>
                        <p>
                            <span><?php echo $answer->text ?></span>
                            <span class="label label-info pull-right">
                                <b><?php echo $this->translate('Votes') ?>:</b> <?php echo $answer->voted ?>
                            </span>
                        </p>
                    <?php endforeach ?>

                <?php endif ?>
            </div>
            <?php echo $this->translate('Question and it\'s answers will be deleted. This operation can not be prevented!') ?>
            <br>
            <a class="btn btn-danger m-t" href="<?php echo $this->url('admin/quiz', array('locale' => $this->currentLocale(), 'action' => 'delete', 'id' => $this->question->id), array('query' => array('confirm' => true))) ?>"><?php echo $this->translate('Delete') ?></a>
        	<a class="btn btn-primary m-t" href="<?php echo $this->url('admin/quiz', array('locale' => $this->currentLocale())) ?>"><?php echo $this->translate('Cancel') ?></a>
        </div>
    </div>
</div>