<?php  
	$this->headTitle()->append($this->translate('Quiz'));
?>
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-sm-4">
        <h2><?php echo $this->translate('Quiz') ?></h2>
        <?php
            $this->plugin('navigation')->setContainer($this->navigation('Zend\Navigation\Admin')->getContainer());

            echo $this->navigation()
                      ->breadcrumbs()
                      ->setMinDepth(0)               
                      ->setMaxDepth(4)         
                      ->setPartial('partial/admin-breadcrumbs');
        ?>
    </div>
	<div class="col-sm-8">
		<div class="title-action">
			<a href="<?php echo $this->url('admin/quiz', array('locale' => $this->currentLocale(), 'action' => 'add')) ?>" class="btn btn-primary">
				<i class="fa fa-fw fa-plus"></i>
				<span><?php echo $this->translate('Add new') ?></span>
			</a>
			<a href="<?php echo $this->url('admin/quiz', array('locale' => $this->currentLocale(), 'action' => 'statsAll')) ?>" class="btn btn-info">
				<i class="fa fa-fw fa-bar-chart"></i>
				<span><?php echo $this->translate('Statistics') ?></span>
			</a>
		</div>
	</div>
</div>
<div class="wrapper wrapper-content">
	<?php if($this->questions): ?>
		<div class="row">
			<div class="col-lg-12">
				<div class="ibox float-e-margins">
					<div class="ibox-title">
						<h5><?php echo $this->translate('Questions') ?></h5>
					</div>
					<div class="ibox-content table-reponsive">
						<table class="table datatable">
							<thead>
								<tr>
									<td>#</td>
									<td><?php echo $this->translate('Question') ?></td>
									<td><?php echo $this->translate('Language') ?></td>
									<td><?php echo $this->translate('Answers count') ?></td>
									<td><?php echo $this->translate('Votes count') ?></td>
									<td></td>
								</tr>
							</thead>
							<tbody>
								<?php $i=1; foreach ($this->questions as $question): ?>
									<tr>
										<td><?php echo $i ?></td>
										<td><?php echo $question->text ?></td>
										<td><?php echo isset($this->locales[$question->locale]) ? $this->locales[$question->locale] : '' ?></td>
										<td <?php if(!$question->countAnswers()) echo 'class="danger"' ?>>
											<span><?php echo $question->countAnswers() ?></span>
										</td>
										<td><?php echo $question->getVotesCount() ?></td>
										<td class="text-right">
											<a class="btn btn-success btn-rounded btn-outline" data-toggle="tooltip" data-placement="top" data-original-title="<?php echo $this->escapeHtmlAttr($this->translate('Edit')) ?>" href="<?php echo $this->url('admin/quiz', array('locale' => $this->currentLocale(), 'action' => 'edit', 'id' => $question->id)) ?>">
												<i class="fa fa-edit"></i>
											</a>
											<a class="btn btn-danger btn-rounded btn-outline" data-toggle="tooltip" data-placement="top" data-original-title="<?php echo $this->escapeHtmlAttr($this->translate('Delete')) ?>" href="<?php echo $this->url('admin/quiz', array('locale' => $this->currentLocale(), 'action' => 'delete', 'id' => $question->id)) ?>">
												<i class="fa fa-trash-o"></i>
											</a>
										</td>
									</tr>
								<?php $i++; endforeach ?>
							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
	<?php else: ?>
		<div class="middle-box text-center alert alert-info">
			<p>
				<i class="fa fa-exclamation fa-3x"></i>
			</p>
	        <h3 class="font-bold"><?php echo $this->translate('There are no questions to display') ?></h3>
	        <div class="error-desc">
	            <?php echo $this->translate('You can add new by clicking link below') ?>
	            <br>
	            <a class="btn btn-info m-t" href="<?php echo $this->url('admin/quiz', array('locale' => $this->currentLocale(), 'action' => 'add')) ?>"><?php echo $this->translate('Add new question') ?></a>
	        </div>
	    </div>
	<?php endif ?>
</div>
<script src="js/plugins/dataTables/jquery.dataTables.js"></script>
<script src="js/plugins/dataTables/dataTables.bootstrap.js"></script>
<script src="js/plugins/dataTables/dataTables.responsive.js"></script>
<script src="js/plugins/dataTables/dataTables.tableTools.min.js"></script>
<?php  
	$this->headStyle()
	->appendStyle("
		.white--space-nowrap
		{
			white-space: nowrap;
		}
	");

	$this->headLink()
	->appendStylesheet($this->basePath('css/plugins/dataTables/dataTables.bootstrap.css'))
	->appendStylesheet($this->basePath('css/plugins/dataTables/dataTables.responsive.css'))
	->appendStylesheet($this->basePath('css/plugins/dataTables/dataTables.tableTools.min.css'))
	->appendStylesheet($this->basePath('css/plugins/dataTables/dataTables.custom.css'));

	$this->inlineScript()
	->appendFile($this->basePath('js/plugins/dataTables/jquery.dataTables.js'))
	->appendFile($this->basePath('js/plugins/dataTables/dataTables.bootstrap.js'))
	->appendFile($this->basePath('js/plugins/dataTables/dataTables.responsive.js'))
	->appendFile($this->basePath('js/plugins/dataTables/dataTables.tableTools.min.js'))
	->appendScript("
		$('.datatable').dataTable({
            //'responsive': true,
            'language': {
                'url': '".$this->url('application/default', array('locale' => $this->currentLocale(), 'controller' => 'jsPlugins', 'action' => 'datatablesI18n'))."'
            }
        });
		$('*[data-toggle=\"tooltip\"]').tooltip();
	");
?>