<?php $this->headTitle()->append($this->translate('Add new useful link'))->append($this->translate('Useful links')); ?>
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-sm-8">
        <h2><?php echo $this->translate('Add new useful link') ?></h2>
        <?php
            echo $this->navigation()
                ->breadcrumbs()
                ->setMinDepth(0)
                ->setMaxDepth(4)
                ->setPartial('partial/admin-breadcrumbs');
        ?>
    </div>
</div>

<div class="wrapper wrapper-content">
	<div class="row">
		<div class="col-lg-12">
			<div class="ibox float-e-margins">
				<div class="ibox-title">
					<h5><?php echo $this->translate('Useful link') ?></h5>
				</div>
				<div class="ibox-content">
					<?php  
						$form = $this->form;

						$form
						->setAttribute('action', $this->url('admin/useful-links', array('locale' => $this->currentLocale(), 'action' => 'add')))
						->prepare();

						$formLabel = $this->plugin('formLabel');

						echo $this->form()->openTag($form);
					?>
						<div class="form-group<?php if($form->get('locale')->getMessages()) echo ' has-error' ?>">
							<?php  
								echo $formLabel->openTag();
									echo $this->translate($form->get('locale')->getOption('label'));
									echo '<span style="color:red;">*</span>';
								echo $formLabel->closeTag(); 
							?>
							<?php 
								echo $this->formSelect
								(
									$form->get('locale')
									->setAttribute('class', 'form-control')
									->setAttribute('id', 'locale-select')
								) 
							?>
							<?php echo $this->formElementErrors($form->get('locale')) ?>
						</div>
						<div class="form-group<?php if($form->get('url')->getMessages()) echo ' has-error' ?>">
							<?php  
								echo $formLabel->openTag();
									echo $this->translate($form->get('url')->getOption('label'));
									echo '<span style="color:red;">*</span>';
								echo $formLabel->closeTag(); 
							?>
							<?php 
								echo $this->formText
								(
									$form->get('url')
									->setAttribute('class', 'form-control')
								) 
							?>
							<?php echo $this->formElementErrors($form->get('url')) ?>
						</div>
						<div class="form-group<?php if($form->get('image')->getMessages()) echo ' has-error' ?>">
							<?php  
								echo $formLabel->openTag();
									echo $this->translate($form->get('image')->getOption('label'));
									echo '<span style="color:red;">*</span>';
								echo $formLabel->closeTag(); 
							?>
							<div id="image-holder">
								<?php if ($this->form->get('image')->getValue()): ?>
									<img src="<?php echo $this->form->get('image')->getValue() ?>" class="img-responsive center-block">
								<?php endif ?>
							</div>
							<br>
							<div class="input-group">
								<?php 
									echo $this->formText
									(
										$form->get('image')
										->setAttribute('id', 'image-input')
										->setAttribute('class', 'form-control')
									) 
								?>
								<div class="input-group-btn">
									<button class="btn btn-white" type="button" id="image-upload">
										<i class="fa fa-cloud-upload"></i>
										<span class="hidden-xs"><?php echo $this->translate('Upload to server') ?></span>
									</button>
									<button class="btn btn-white" type="button" id="image-explore">
										<i class="fa fa-folder"></i>
										<span class="hidden-xs"><?php echo $this->translate('Choose from server') ?></span>
									</button>
								</div>
							</div>
							<?php echo $this->formElementErrors($form->get('image')) ?>
						</div>
						<div class="form-group<?php if($form->get('title')->getMessages()) echo ' has-error' ?>">
							<?php  
								echo $formLabel->openTag();
									echo $this->translate($form->get('title')->getOption('label'));
									echo '<span style="color:red;">*</span>';
								echo $formLabel->closeTag(); 
							?>
							<?php 
								echo $this->formText
								(
									$form->get('title')
									->setAttribute('class', 'form-control')
								) 
							?>
							<?php echo $this->formElementErrors($form->get('title')) ?>
						</div>
						<div class="form-group<?php if($form->get('order')->getMessages()) echo ' has-error' ?>">
							<?php echo $this->formLabel($form->get('order')) ?>
							<?php 
								echo $this->formSelect
								(
									$form->get('order')
									->setAttribute('class', 'form-control')
									->setAttribute('id', 'editor')
								) 
							?>
							<?php echo $this->formElementErrors($form->get('order')) ?>
						</div>
						<div class="clearfix"></div>
						<button type="submit" class="btn btn-success">
							<span><?php echo $this->translate('Add') ?></span>
						</button>
						<a href="<?php echo $this->url('admin/useful-links', array('locale' => $this->currentLocale())) ?>" class="btn btn-warning">
							<span><?php echo $this->translate('Cancel') ?></span>
						</a>
					<?php echo $this->form()->closeTag() ?>
				</div>
			</div>
		</div>
	</div>
</div>
<?php
	$this->headLink()
	->appendStylesheet($this->basePath('dist/plugins/jsTree/themes/default/style.min.css'));

	$this->headStyle()->appendStyle("
		@media screen and (min-width: 769px) {
		  .modal-lg{
		      width:900px;
		  }

		  .modal-sm{
		      width:300px;
		  }
		}

		.modal #progress, .modal .alert {
			margin-top: 30px;
		}

		.modal #progress .progress {
			margin-bottom: 0px;
		}
	");

	$this->inlineScript()
    	->appendFile($this->basePath('dist/plugins/jsTree/jstree.min.js'))
    	->appendFile($this->basePath('dist/js/server-files.js'))
    	->appendScript("
    		$.serverFiles.dirsRoute      = '" . $this->url('admin/default', array('locale' => $this->currentLocale(), 'controller' => 'files', 'action' => 'jsTree')) . "';
    		$.serverFiles.filesRoute     = '" . $this->url('admin/default', array('locale' => $this->currentLocale(), 'controller' => 'files', 'action' => 'fetch')) . "';
    		$.serverFiles.newFolderRoute = '" . $this->url('admin/default', array('locale' => $this->currentLocale(), 'controller' => 'files', 'action' => 'operate')) . "';
    		$.serverFiles.renameRoute    = '" . $this->url('admin/default', array('locale' => $this->currentLocale(), 'controller' => 'files', 'action' => 'operate')) . "';
    		$.serverFiles.deleteRoute    = '" . $this->url('admin/default', array('locale' => $this->currentLocale(), 'controller' => 'files', 'action' => 'operate')) . "';
    		$.serverFiles.moveRoute      = '" . $this->url('admin/default', array('locale' => $this->currentLocale(), 'controller' => 'files', 'action' => 'operate')) . "';
    		$.serverFiles.locale         = {
    			'title': '".$this->escapeHtmlAttr($this->translate('Server files explorer'))."',
    			'close': '".$this->escapeHtmlAttr($this->translate('Close'))."',
    			'loading': '".$this->escapeHtmlAttr($this->translate('Loading...'))."',
    			'renameOnlyOne': '".$this->escapeHtmlAttr($this->translate('You can rename only one file at a time'))."',
                'newName'   : '".$this->escapeHtmlAttr($this->translate('New name:'))."',
                'sure'      : '".$this->escapeHtmlAttr($this->translate('Are you sure?'))."',
                'onlyOneNewFolder': '".$this->escapeHtmlAttr($this->translate('You can create only one folder at a time'))."',
                'choose'    : '".$this->escapeHtmlAttr($this->translate('Choose'))."',
                'newFolder' : '".$this->escapeHtmlAttr($this->translate('New folder'))."',
                'rename'    : '".$this->escapeHtmlAttr($this->translate('Rename'))."',
                'delete'    : '".$this->escapeHtmlAttr($this->translate('Delete'))."',
                'refresh'   : '".$this->escapeHtmlAttr($this->translate('Refresh'))."'
    		};

    		$('#image-upload').click(function (evt) {
                var modal = {
                    isUploading: true,
                    template: String() +
                        '<div class=\"modal\">'+
                            '<div class=\"modal-dialog\">'+
                                '<div class=\"modal-content\">'+
                                    '<div class=\"modal-header\">'+
                                        '<button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\"><span aria-hidden=\"true\">&times;</span></button>'+
                                        '<h4 class=\"modal-title\">".$this->escapeHtmlAttr($this->translate('Upload files to server'))."</h4>'+
                                    '</div>'+
                                    '<div class=\"modal-body\">'+
                                        '<form method=\"POST\" enctype=\"multipart/form-data\" id=\"_editor-fileupload\" action=\"".$this->url('admin/default', array('locale' => $this->currentLocale(), 'controller' => 'files', 'action' => 'upload'))."\">'+
                                            '<input id=\"uploads\" name=\"uploads[]\" type=\"file\" multiple=\"multiple\" class=\"hidden\">'+
                                        '</form>'+
                                        '<button id=\"upload-button\" type=\"button\" class=\"btn btn-success\" disabled=\"disabled\">' +
                                            '<i class=\"fa fa-arrow-circle-o-up\"></i> ".$this->escapeHtmlAttr($this->translate('Start upload'))." '+
                                        '</button> ' + 
                                        '<button id=\"choose-files\" type=\"button\" class=\"btn btn-primary\">' +
                                            '<i class=\"fa fa-th\"></i> ".$this->escapeHtmlAttr($this->translate('Choose files'))." ' +
                                        '</button> ' +
                                        '<span class=\"files-count\"></span>' +
                                        '<div id=\"progress\"></div>' +
                                    '</div>'+
                                    '<div class=\"modal-footer\">'+
                                        '<button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">".$this->escapeHtmlAttr($this->translate('Close'))."</button>'+
                                    '</div>'+
                                '</div>'+
                            '</div>'+
                        '</div>',
                    remove: function(){
                        if(!this.current)
                            return;

                        var current = this.current;

                        setTimeout(function(){
                            this.current.remove();
                        }, 600);
                    },
                };

                modal.current = $(modal.template);

                $('body').append(modal.current);

                modal.current.modal('show');
                modal.current.find('.modal-footer .btn').click(modal.remove);
                modal.current.find('.modal-header .close').click(modal.remove);
                modal.current.find('#upload-button').click(uploadFiles);
                modal.current.find('#choose-files').click(chooseFiles);
                modal.current.find('#uploads').change(pickFiles);

                function pickFiles() {
                    var label = modal.current.find('.modal-body span.files-count');
                    var text  = (this.files.length == 1) ? '".str_replace("'", "", $this->translate('Selected %s file'))."' : '".str_replace("'", "", $this->translate('Selected %s files'))."'; 
                    
                    text = text.replace('%s', this.files.length);
                    label.text(text);

                    if (this.files.length) {
                        modal.current.find('#upload-button').removeAttr('disabled');
                    }
                    else {
                        modal.current.find('#upload-button').attr('disabled', 'disabled');
                    }

                }

                function chooseFiles() {
                    modal.current.find('#uploads').click();
                }

                function uploadFiles() {
                    var input = modal.current.find('#uploads');
                    if (input[0].files.length > 0) {
                        $.ajax({
                            xhr: function(){
                                var xhr = $.ajaxSettings.xhr();

                                if(xhr.upload)
                                {
                                    var container = modal.current.find('#progress');
                                    container.empty();

                                    var progressTemplate = String() +
                                        '<div class=\"progress\">' +
                                            '<div class=\"progress-bar progress-bar-success progress-bar-striped active\" role=\"progressbar\">' +
                                            '</div>' +
                                        '</div>';
                                    
                                    var progress = $(progressTemplate);
                                    progress.appendTo(container);

                                    xhr.upload.addEventListener('progress', function(e) {
                                        progress.find('.progress-bar').css('width', e.loaded / e.total * 100);
                                    });
                                }

                                return xhr;
                            },
                            url: '".$this->url('admin/default', array('locale' => $this->currentLocale(), 'controller' => 'files', 'action' => 'upload'))."',
                            type: 'post',
                            data: new FormData(modal.current.find('form')[0]),
                            cache: false,
                            processData: false,
                            contentType: false,
                            dataType: 'json',
                            beforeSend: function(xhr, settings) {
                                modal.current.find('.modal-body .alert').slideUp('fast', function() {
                                    $(this).remove();
                                });
                            },
                            success: function(data, status, xhr) {
                                var progress = modal.current.find('#progress .progress');
                                var alert = $(
                                    '<div class=\"alert alert-' + ((data.status == true) ? 'info' : 'danger') + ' alert-dismissible\" role=\"alert\" style=\"display: none;\">' + 
                                        '<button type=\"button\" class=\"close\" data-dismiss=\"alert\" aria-label=\"Close\"><span aria-hidden=\"true\">&times;</span></button>' +
                                        data.messages.join('<br>') +
                                    '</div>'
                                );

                                progress.slideUp('fast', function() { $(this).remove(); });
                                alert.insertBefore(modal.current.find('#progress')).slideDown('fast');
                            },
                            error: function(xhr, status, error) {
                                var progress = modal.current.find('#progress .progress');
                                var alert = $(
                                    '<div class=\"alert alert-danger alert-dismissible\" role=\"alert\" style=\"display: none;\">' + 
                                        '<button type=\"button\" class=\"close\" data-dismiss=\"alert\" aria-label=\"Close\"><span aria-hidden=\"true\">&times;</span></button>' +
                                        error +
                                    '</div>'
                                );

                                progress.slideUp('fast', function() { $(this).remove(); });
                                alert.insertBefore(modal.current.find('#progress')).slideDown('fast');
                            }
                        });
                    }
                }
            });

    		$('#image-explore').click(function(){
    			$.serverFiles.createModal();
    		});

    		$.serverFiles.fileAdd = function(files){
    	        for(var i=0; i<files.length; i++)
    	        {
    	            if(files[i].path.charAt(0) == '/')
    	            {
    	                files[i].path = files[i].path.substr(1);
    	            }

    	            if(/(jp?g|png|gif)$/i.test(files[i].extension))
    	            {
    	            	$('#image-input').val(files[i].path);
    	            	$('#image-input').trigger('change');
    	            }
    	            else
    	            {
    	            	alert('".$this->escapeHtmlAttr($this->translate('Only images can be selected'))."');
    	            }
    				
    				// select only one image
    	            return;
    	        }
    	    };

    	    $('#image-input').on('change', function(){
    	    	$('#image-holder').html('<img src=\"'+$(this).val().trim()+'\" class=\"img-responsive center-block\">');
    	    });
    	
    		if($('#image-input').val().trim())
    		{
    	    	$('#image-input').trigger('change');
    		}
    	");
?>