<?php  
    echo $this->headTitle()
        ->append($this->translate('Useful links'));
    echo $this->headLink()
        ->appendStylesheet($this->basePath('dist/plugins/dataTables/dataTables.bootstrap.css'))
        ->appendStylesheet($this->basePath('dist/plugins/dataTables/dataTables.responsive.css'))
        ->appendStylesheet($this->basePath('dist/plugins/dataTables/dataTables.tableTools.min.css'))
        ->appendStylesheet($this->basePath('dist/plugins/dataTables/dataTables.custom.css'));
    echo $this->headStyle()
        ->appendStyle("
            .white--space-nowrap {
                white-space: nowrap;
            }
        ");
?>
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-sm-4">
        <h2><?php echo $this->translate('Useful links') ?></h2>
        <?php
            $this->plugin('navigation')->setContainer($this->navigation('Zend\Navigation\Admin')->getContainer());

            echo $this->navigation()
                ->breadcrumbs()
                ->setMinDepth(0)
                ->setMaxDepth(4)
                ->setPartial('partial/admin-breadcrumbs');
        ?>
    </div>
    <div class="col-sm-8">
        <div class="title-action">
            <a href="<?php echo $this->url('admin/useful-links', array('locale' => $this->currentLocale(), 'action' => 'add')) ?>" class="btn btn-primary">
                <i class="fa fa-fw fa-plus"></i>
                <span><?php echo $this->translate('Add new') ?></span>
            </a>
        </div>
    </div>
</div>
<div class="wrapper wrapper-content">
    <?php if($this->links): ?>
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5><?php echo $this->translate('Useful links') ?></h5>
                    </div>
                    <div class="ibox-content table-reponsive">
                        <table class="table datatable">
                            <thead>
                                <tr>
                                    <td>#</td>
                                    <td><?php echo $this->translate('Image') ?></td>
                                    <td><?php echo $this->translate('URL') ?></td>
                                    <td><?php echo $this->translate('Title') ?></td>
                                    <td><?php echo $this->translate('Language') ?></td>
                                    <td></td>
                                </tr>
                            </thead>
                            <tbody>
                                <?php $i=1; foreach ($this->links as $link): ?>
                                    <tr>
                                        <td><?php echo $i ?></td>
                                        <td>
                                            <img src="<?php echo $link->image ?>" alt="<?php echo $link->image ?>" class="img-responsive">
                                        </td>
                                        <td>
                                            <a target="_blank" href="<?php echo $link->url ?>">
                                                <span><?php echo $link->url ?></span>
                                            </a>
                                        </td>
                                        <td><?php echo $link->title ?></td>
                                        <td><?php echo isset($this->locales[$link->locale])? $this->locales[$link->locale]: '-' ?></td>
                                        <td>
                                            <a class="btn btn-default btn-rounded btn-outline" data-toggle="tooltip" data-original-title="<?php echo $this->escapeHtmlAttr($this->translate('Edit')) ?>" href="<?php echo $this->url('admin/useful-links', array('locale' => $this->currentLocale(), 'action' => 'edit', 'id' => $link->id)) ?>">
                                                <i class="fa fa-edit fa-fw"></i>
                                            </a>
                                            <a class="btn btn-default btn-rounded btn-outline btn-danger" data-toggle="tooltip" data-original-title="<?php echo $this->escapeHtmlAttr($this->translate('Delete')) ?>" href="<?php echo $this->url('admin/useful-links', array('locale' => $this->currentLocale(), 'action' => 'delete', 'id' => $link->id)) ?>">
                                                <i class="fa fa-trash-o fa-fw"></i>
                                            </a>
                                        </td>
                                    </tr>
                                <?php $i++; endforeach ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    <?php else: ?>
        <div class="middle-box text-center alert alert-info">
            <p>
                <i class="fa fa-exclamation fa-3x"></i>
            </p>
            <h3 class="font-bold"><?php echo $this->translate('There are no links to display') ?></h3>
            <div class="error-desc">
                <?php echo $this->translate('You can add new by clicking link below') ?>
                <br>
                <a class="btn btn-info m-t" href="<?php echo $this->url('admin/useful-links', array('locale' => $this->currentLocale(), 'action' => 'add')) ?>"><?php echo $this->translate('Add new useful link') ?></a>
            </div>
        </div>
    <?php endif ?>
</div>

<?php
    echo $this->inlineScript()
        ->appendFile($this->basePath('dist/plugins/dataTables/jquery.dataTables.js'))
        ->appendFile($this->basePath('dist/plugins/dataTables/dataTables.bootstrap.js'))
        ->appendFile($this->basePath('dist/plugins/dataTables/dataTables.responsive.js'))
        ->appendFile($this->basePath('dist/plugins/dataTables/dataTables.tableTools.min.js'))
        ->appendScript("
            $('.datatable').dataTable({
                //'responsive': true,
                'language': {
                    'url': '".$this->url('application/default', array('locale' => $this->currentLocale(), 'controller' => 'jsPlugins', 'action' => 'datatablesI18n'))."'
                }
            });
            $('*[data-toggle=\"tooltip\"]').tooltip();
        ");
?>