<?php
    $this->headTitle()
        ->append($this->translate('Add new page'))
        ->append($this->translate('Pages management'));
    $this->headLink()
        ->appendStylesheet($this->basePath('dist/plugins/jsTree/themes/default/style.min.css'))
        ->appendStylesheet($this->basePath('dist/plugins/summernote/summernote.css'))
        ->appendStylesheet($this->basePath('dist/plugins/summernote/summernote-bs3.css'))
        ->appendStylesheet($this->basePath('dist/plugins/codemirror/codemirror.css'))
        ->appendStylesheet($this->basePath('dist/plugins/codemirror/theme/monokai.css'))
        ->appendStylesheet($this->basePath('dist/plugins/chosen/chosen.css'))
        ->appendStylesheet($this->basePath('dist/plugins/iCheck/custom.css'));
    $this->headStyle()
        ->appendStyle(
            "
                @media screen and (min-width: 769px) {
                    .modal-lg {
                        width:900px;
                    }

                    .modal-sm {
                        width:300px;
                    }
                }
                .modal #progress, .modal .alert {
                    margin-top: 30px;
                }
                .modal #progress .progress {
                    margin-bottom: 0px;
                }
            "
        );
?>

<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-sm-8">
        <h2><?php echo $this->translate('Add new page') ?></h2>
        <?php
            $this->plugin('navigation')->setContainer(
                $this->navigation('Zend\Navigation\Admin')->getContainer()
            );

            echo $this->navigation()
                ->breadcrumbs()
                ->setMinDepth(0)
                ->setMaxDepth(4)
                ->setPartial('partial/admin-breadcrumbs');
        ?>
    </div>
</div>

<div class="wrapper wrapper-content">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5><?php echo $this->translate('Page properties') ?></h5>
                </div>

                <div class="ibox-content">
                    <?php  
                        $form = $this->form;

                        $form->setAttribute('action', $this->url('admin/pages', ['locale' => $this->currentLocale(), 'action' => 'add']));
                        $form->prepare();

                        $formLabel = $this->plugin('formLabel');

                        echo $this->form()->openTag($form);
                    ?>

                    <?php if($this->errors): ?>
                        <div class="alert alert-danger">
                            <?php foreach($this->errors as $error): ?>
                                <b><?php echo $this->translate($error) ?></b>
                            <?php endforeach; ?>
                        </div>
                    <?php endif; ?>

                    <div class="form-group<?php if($form->get('locale')->getMessages()) echo ' has-error' ?>">
                        <?php  
                            echo $formLabel->openTag();
                            echo $this->translate($form->get('locale')->getOption('label'));
                            echo '<span style="color:red;">*</span>';
                            echo $formLabel->closeTag();
                            echo $this->formSelect(
                                $form->get('locale')
                                    ->setAttribute('class', 'form-control')
                                    ->setAttribute('id', 'locale-select')
                            );
                            echo $this->formElementErrors($form->get('locale'));
                        ?>
                    </div>

                    <div class="form-group<?php if($form->get('title')->getMessages()) echo ' has-error' ?>">
                        <?php  
                            echo $formLabel->openTag();
                            echo $this->translate($form->get('title')->getOption('label'));
                            echo '<span style="color:red;">*</span>';
                            echo $formLabel->closeTag(); 
                        ?>
                        <?php 
                            echo $this->formText(
                                $form->get('title')
                                    ->setAttribute('class', 'form-control')
                            );
                        ?>
                        <?php echo $this->formElementErrors($form->get('title')) ?>
                    </div>

                    <div class="form-group<?php if($form->get('visible')->getMessages()) echo ' has-error' ?>">
                        <?php echo $formLabel->openTag(); ?>
                        <?php 
                            echo $this->formCheckbox(
                                $form->get('visible')
                                    ->setAttribute('class', 'i-checks')
                            ), '&nbsp;&nbsp;';

                            echo $this->translate($form->get('visible')->getOption('label'));
                        ?>
                        <?php echo $formLabel->closeTag();  ?>
                        <?php echo $this->formElementErrors($form->get('visible')) ?>
                    </div>

                    <div class="form-group<?php if($form->get('body')->getMessages()) echo ' has-error' ?>">
                        <?php echo $this->formLabel($form->get('body')) ?>
                        <?php 
                            echo $this->formTextarea(
                                $form->get('body')
                                    ->setAttribute('class', 'form-control')
                                    ->setAttribute('id', 'editor')
                            );
                        ?>
                        <?php echo $this->formElementErrors($form->get('body')) ?>
                    </div>

                    <div class="clearfix"></div>
                    <button type="submit" class="btn btn-success">
                        <span><?php echo $this->translate('Add') ?></span>
                    </button>
                    <a href="<?php echo $this->url('admin/pages', array('locale' => $this->currentLocale())) ?>" class="btn btn-warning">
                        <span><?php echo $this->translate('Cancel') ?></span>
                    </a>
                    <?php echo $this->form()->closeTag() ?>
                </div>
            </div>
        </div>
    </div>
</div>

<?php
    $this->inlineScript()
        ->appendFile($this->basePath('dist/plugins/jsTree/jstree.min.js'))
        ->appendFile($this->basePath('dist/plugins/summernote/summernote.min.js'))
        ->appendFile($this->basePath('dist/plugins/summernote/buttons/files-explorer.js'))
        ->appendFile($this->basePath('dist/plugins/summernote/buttons/fetch.js'))
        ->appendFile($this->basePath('dist/plugins/codemirror/codemirror.js'))
        ->appendFile($this->basePath('dist/plugins/codemirror/mode/xml/xml.js'))
        ->appendFile($this->basePath('dist/plugins/codemirror/mode/javascript/javascript.js'))
        ->appendFile($this->basePath('dist/plugins/codemirror/formatting.js'))
        ->appendFile($this->basePath('dist/plugins/chosen/chosen.jquery.js'))
        ->appendFile($this->basePath('dist/plugins/iCheck/icheck.min.js'));

    $this->inlineScript()
        ->appendFile($this->basePath('dist/js/server-files.js'));

    if($this->currentLocale() != 'en-US') {
        $this->inlineScript()
            ->appendFile($this->basePath('dist/plugins/summernote/locales/'.$this->currentLocale().'.js'));
    }

    $this->inlineScript()->appendScript("
        $(window).ready(function() {
            $('#editor').summernote({
                height: 500,
                lang: '".$this->currentLocale()."',
                fileUploadRoute: '".$this->url('admin/default', ['locale' => $this->currentLocale(), 'controller' => 'files', 'action' => 'upload'])."',
                toolbar: [
                    ['timeline', ['undo', 'redo']],
                    ['style', ['style']],
                    ['font-style', ['fontname', 'bold', 'italic', 'underline', 'color', 'clear']],
                    ['font', ['strikethrough', 'superscript', 'subscript']],
                    ['para', ['ul', 'ol', 'hr', 'paragraph']],
                    ['table', ['table', 'link', 'fetcher']],
                    ['height', ['height']],
                    ['files', ['filesUpload', 'video', 'files']],
                    ['misc', ['codeview', 'fullscreen', 'help']]
                ],
                buttons: {
                    files: FilesExplorer,
                    filesUpload: FilesUpload,
                    fetcher: _SummernoteFetcher,
                },
                codemirror: {
                    theme: 'monokai',
                    font: 72,
                    dialogsFade: true
                },
                fetcher: {
                    route: '".$this->url('admin/default', ['locale' => $this->currentLocale(), 'controller' => 'fetch', 'action' => 'bySearch'])."'
                }
            });
        });

        $.serverFiles.dirsRoute      = '" . $this->url('admin/default', array('locale' => $this->currentLocale(), 'controller' => 'files', 'action' => 'jsTree')) . "';
        $.serverFiles.filesRoute     = '" . $this->url('admin/default', array('locale' => $this->currentLocale(), 'controller' => 'files', 'action' => 'fetch')) . "';
        $.serverFiles.newFolderRoute = '" . $this->url('admin/default', array('locale' => $this->currentLocale(), 'controller' => 'files', 'action' => 'operate')) . "';
        $.serverFiles.renameRoute    = '" . $this->url('admin/default', array('locale' => $this->currentLocale(), 'controller' => 'files', 'action' => 'operate')) . "';
        $.serverFiles.deleteRoute    = '" . $this->url('admin/default', array('locale' => $this->currentLocale(), 'controller' => 'files', 'action' => 'operate')) . "';
        $.serverFiles.moveRoute      = '" . $this->url('admin/default', array('locale' => $this->currentLocale(), 'controller' => 'files', 'action' => 'operate')) . "';

        $.serverFiles.locale = {
            'title'            : '".$this->escapeHtmlAttr($this->translate('Server files explorer'))."',
            'close'            : '".$this->escapeHtmlAttr($this->translate('Close'))."',
            'loading'          : '".$this->escapeHtmlAttr($this->translate('Loading...'))."',
            'renameOnlyOne'    : '".$this->escapeHtmlAttr($this->translate('You can rename only one file at a time'))."',
            'newName'          : '".$this->escapeHtmlAttr($this->translate('New name:'))."',
            'sure'             : '".$this->escapeHtmlAttr($this->translate('Are you sure?'))."',
            'onlyOneNewFolder' : '".$this->escapeHtmlAttr($this->translate('You can create only one folder at a time'))."',
            'choose'           : '".$this->escapeHtmlAttr($this->translate('Choose'))."',
            'newFolder'        : '".$this->escapeHtmlAttr($this->translate('New folder'))."',
            'rename'           : '".$this->escapeHtmlAttr($this->translate('Rename'))."',
            'delete'           : '".$this->escapeHtmlAttr($this->translate('Delete'))."',
            'refresh'          : '".$this->escapeHtmlAttr($this->translate('Refresh'))."'
        };

        $('.i-checks').iCheck({
            checkboxClass: 'icheckbox_square-green',
            radioClass: 'iradio_square-green',
        });
    ");
?>