<?php  
    echo $this->headTitle()
        ->append($this->translate('Events'));
?>

<div class="page-view">
    <ol class="breadcrumb">
        <li>
            <a href="<?php
                echo $this->url(
                    'home-locale', 
                    array(
                        'locale' => $this->currentLocale())) ?>">
                <?php echo $this->translate('Home') ?>
            </a>
        </li>
        <li class="active">
            <?php echo $this->translate('Events'); ?>
        </li>
    </ol>

    <div class="page-content">
        <?php if ($this->posts->count()): ?>
            <?php foreach ($this->posts as $post): ?>
                <section>
                    <h4>
                        <a href="<?php
                            echo $this->url(
                                'events/view',
                                array(
                                    'locale' => $this->currentLocale(),
                                    'page' => $post->url
                                )
                            );
                        ?>">
                            <?php echo $post->title; ?>
                        </a>
                    </h4>

                    <div class="item">
                        <i class="ezo-calendar"></i>
                        <?php echo date('d-m-Y', $post->added); ?>
                        <span>
                            <?php if ($post->happens <= time()): ?>
                                <?php echo $this->translate('Happened') ?>
                            <?php else: ?>
                                <?php echo $this->translate('Happens') ?>
                            <?php endif ?>
                        </span>
                    </div>
                </section>
                <hr>
            <?php endforeach ?>
        <?php else: ?>
            <div class="alert alert-info text-center">
                <i class="fa fa-edit fa-2x"></i>
                <h3>
                    <?php echo $this->translate('Information will be added soon') ?>
                </h3>
            </div>
        <?php endif ?>

        <?php 
            echo $this->paginationControl(
                $this->posts,
                'Sliding',
                'pages/partial/blog-paginator', 
                array(
                    'route' => 'events/wall',
                )
            ); 
        ?>
    </div>
</div>