<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \Pages\ArrayObject\News $news
 */
$this->headTitle()->append($this->translate('News'));
$order = 1;
?>

<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-sm-8">
        <h2><?php echo $this->translate('News') ?></h2>

        <?php
            echo $this->navigation('Zend\Navigation\Admin')
            ->breadcrumbs()
            ->setMinDepth(0)
            ->setMaxDepth(4)
            ->setPartial('partial/admin-breadcrumbs');
        ?>
    </div>

    <div class="col-sm-4">
        <div class="title-action">
            <a class="btn btn-primary" href="<?php
                echo $this->url(
                    'admin/news',
                    [
                        'locale' => $this->currentLocale(),
                        'action' => 'add'
                    ]
                )
            ?>">
                <?php echo $this->translate('Add news') ?>
            </a>
        </div>
    </div>
</div>

<div class="wrapper wrapper-content">
    <?php if ($this->news) : ?>
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5><?php echo $this->translate('News') ?></h5>

                        <div class="ibox-tools">
                            <a class="collapse-link">
                                <i class="fa fa-chevron-down"></i>
                            </a>
                        </div>
                    </div>

                    <div class="ibox-content table-responsive">
                        <table class="table datatable">
                            <thead>
                                <th>#</th>
                                <th><?php echo $this->translate('Title') ?></th>
                                <th><?php echo $this->translate('Info') ?></th>
                                <th><?php echo $this->translate('Action') ?></th>
                            </thead>

                            <tbody>
                                <?php foreach ($this->news as $news) : ?>
                                    <tr>
                                        <td><?php echo $order ?></td>
                                        <td><?php echo $news->title ?></td>
                                        <td>
                                            <p>
                                                <i class="fa fa-calendar-o fa-fw" style="vertical-align: middle"></i>
                                                <span style="vertical-align: middle"><?php echo date('d-m-Y', $news->added) ?></span>
                                            </p>

                                            <span class="label label-info">
                                                <b><?php echo $this->translate('Category') ?>:</b>
                                                <?php echo $this->categories[$news->category]->title ?>
                                            </span>
                                        </td>
                                        <td>
                                            <a
                                                href="<?php
                                                    echo $this->url(
                                                        'news/view',
                                                        [
                                                            'locale' => $news->locale,
                                                            'category' => $this->categories[$news->category]->url,
                                                            'id' => $news->id
                                                        ]
                                                    )
                                                ?>"
                                                target="_blank"
                                                class="btn btn-default btn-rounded btn-outline"
                                                data-toggle="tooltip"
                                                data-placement="top"
                                                data-original-title="<?php echo $this->escapeHtmlAttr($this->translate('View')) ?>"
                                            >
                                                <i class="fa fa-external-link"></i>
                                            </a>

                                            <a
                                                class="btn btn-default btn-rounded btn-outline"
                                                data-toggle="tooltip"
                                                data-placement="top"
                                                data-original-title="<?php echo $this->escapeHtmlAttr($this->translate('Edit')) ?>"
                                                href="<?php
                                                    echo $this->url(
                                                        'admin/news',
                                                        [
                                                            'locale' => $this->currentLocale(),
                                                            'action' => 'edit',
                                                            'id' => $news->id
                                                        ]
                                                    )
                                                ?>"
                                            >
                                                <i class="fa fa-edit"></i>
                                            </a>

                                            <a
                                                class="btn btn-default btn-rounded btn-outline"
                                                data-toggle="tooltip"
                                                data-placement="top"
                                                data-original-title="<?php echo $this->escapeHtmlAttr($this->translate('Delete')) ?>"
                                                href="<?php
                                                    echo $this->url(
                                                        'admin/news',
                                                        [
                                                            'locale' => $this->currentLocale(),
                                                            'action' => 'delete',
                                                            'id' => $news->id
                                                        ]
                                                    )
                                                ?>"
                                            >
                                                <i class="fa fa-trash-o"></i>
                                            </a>
                                        </td>
                                    </tr>
                                    <?php $order++ ?>
                                <?php endforeach; ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    <?php else : ?>
        <div class="middle-box text-center alert alert-info">
            <h3 class="font-bold"><?php echo $this->translate('There are no news to display') ?></h3>

            <div class="error-desc">
                <?php echo $this->translate('You can add new one by clicking link below') ?>
                <br>
                <a class="btn btn-info m-t" href="<?php
                    echo $this->url(
                        'admin/news',
                        [
                            'locale' => $this->currentLocale(),
                            'action' => 'add'
                        ]
                    )
                ?>">
                    <?php echo $this->translate('Add news') ?>
                </a>
            </div>
        </div>
    <?php endif; ?>
</div>

<?php
$this->headStyle()
    ->appendStyle("
        .white--space-nowrap {
            white-space: nowrap;
        }
    ");

$this->headLink()
->appendStylesheet($this->basePath('dist/plugins/dataTables/dataTables.bootstrap.css'))
->appendStylesheet($this->basePath('dist/plugins/dataTables/dataTables.responsive.css'))
->appendStylesheet($this->basePath('dist/plugins/dataTables/dataTables.tableTools.min.css'))
->appendStylesheet($this->basePath('dist/plugins/dataTables/dataTables.custom.css'));

$this->inlineScript()
->appendFile($this->basePath('dist/plugins/dataTables/jquery.dataTables.js'))
->appendFile($this->basePath('dist/plugins/dataTables/dataTables.bootstrap.js'))
->appendFile($this->basePath('dist/plugins/dataTables/dataTables.responsive.js'))
->appendFile($this->basePath('dist/plugins/dataTables/dataTables.tableTools.min.js'))
->appendScript("
    $('.datatable').dataTable({
        'responsive': true,
        'language': {
            'url': '".$this->url('application/default', ['locale' => $this->currentLocale(), 'controller' => 'jsPlugins', 'action' => 'datatablesI18n'])."'
        }
    });
    $('*[data-toggle=\"tooltip\"]').tooltip();
");
?>
