<?php echo $this->headTitle()->append($this->translate('Delete image collection'))->append($this->translate('Media')) ?>
<?php $mediaConfig = $this->getHelperPluginManager()->getServiceLocator()->get('config')['media']; ?>
<div class="row wrapper border-bottom white-bg page-heading">
	<div class="col-sm-8">
		<h2><?php echo $this->translate('Delete image collection') ?></h2>
		<?php
            $this->plugin('navigation')->setContainer($this->navigation('Zend\Navigation\Admin')->getContainer());

            echo $this->navigation()
                      ->breadcrumbs()
                      ->setMinDepth(0)               
                      ->setMaxDepth(4)         
                      ->setPartial('partial/admin-breadcrumbs');
        ?>
	</div>
	<div class="col-sm-4">
		<div class="title-action">
            <a class="btn btn-primary" href="<?php echo $this->url('admin/media', array('locale' => $this->currentLocale(), 'action' => 'collections')) ?>">
            	<i class="fa fa-arrow-left"></i>
            	<?php echo $this->translate('Back'); ?>
            </a>
        </div>
	</div>
</div>
<div class="wrapper wrapper-content">
	<div class="row">
		<div class="col-lg-12">
			<div class="ibox float-e-margins">
				<div class="ibox-title">
					<h5><?php echo $this->translate('Delete image collection'); ?></h5>
					<div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-down"></i>
                        </a>
                    </div>
				</div>
				<div class="ibox-content">
				<h2><?php echo $this->translate('Image collection') . ": " . $this->collectionName; ?></h2>
				<?php foreach ($this->collection as $cn) : ?>
					<?php $src = $mediaConfig['public_path'] . "collection_" . $cn->name . "/" . $cn->src; ?>
					<div class="img-wrapper">
						<img src="<?php echo $this->basePath($src); ?>" alt="" class="img-responsive img-thumbnail">
					</div>
				<?php endforeach; ?>
				<?php if ($this->gallery && $this->gallery->count()) : ?>
				<h2><?php echo $this->translate('Used in'); ?>:</h2>
				<?php foreach ($this->gallery as $gl) : ?>
				<h4><?php echo $this->translate('Gallery') . ": " . $gl->title; ?></h4>
				<?php endforeach; ?>
				<div class="alert alert-warning text-center">
					<h2><i class="fa fa-info-circle"></i></h2>
					<?php echo $this->translate('If you delete this collection the galleries will be deleted with this collection'); ?>
				</div>
				<?php endif; ?>
				<form action="" method="post">
					<h4><?php echo $this->translate('Do you want to delete this image collection ?'); ?></h4>
					<div class="form-group">
						<button type="submit" class="btn btn-danger">
							<i class="fa fa-trash"></i>
							<?php echo $this->translate('Delete'); ?>
						</button>
						<a href="<?php echo $this->url('admin/media', array('locale' => $this->currentLocale(), 'action' => 'collections')); ?>" class="btn btn-default">
							<i class="fa fa-remove"></i>
							<?php echo $this->translate('Cancel'); ?>
						</a>
					</div>
				</form>
				</div>
			</div>
		</div>
	</div>
</div>