<?php echo $this->headTitle()->append($this->translate('Delete video'))->append($this->translate('Media')) ?>
<?php $locales = $this->getHelperPluginManager()->getServiceLocator()->get('config')['translator']['locales']; ?>
<div class="row wrapper border-bottom white-bg page-heading">
	<div class="col-sm-8">
		<h2><?php echo $this->translate('Delete video') ?></h2>
		<?php
            $this->plugin('navigation')->setContainer($this->navigation('Zend\Navigation\Admin')->getContainer());

            echo $this->navigation()
                      ->breadcrumbs()
                      ->setMinDepth(0)               
                      ->setMaxDepth(4)         
                      ->setPartial('partial/admin-breadcrumbs');
        ?>
	</div>
	<div class="col-sm-4">
		<div class="title-action">
            <a class="btn btn-primary" href="<?php echo $this->url('admin/media', array('locale' => $this->currentLocale(), 'action' => 'videos')) ?>">
            	<i class="fa fa-arrow-left"></i>
            	<?php echo $this->translate('Back'); ?>
            </a>
        </div>
	</div>
</div>
<div class="wrapper wrapper-content">
	<div class="row">
		<div class="col-lg-12">
			<div class="ibox float-e-margins">
				<div class="ibox-title">
					<h5><?php echo $this->translate('Delete video'); ?></h5>
					<div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-down"></i>
                        </a>
                    </div>
				</div>
				<div class="ibox-content">
					<h4><?php echo $this->translate('Video'); ?></h4>	
					<div class="preview" style="margin-bottom: 25px;">
						<?php echo $this->video->src; ?>
					</div>
					<?php if (count($this->descriptions) > 0) : ?>
					<h2><?php echo $this->translate('Descriptions to video'); ?></h2>
					<?php foreach ($this->descriptions as $desc) : ?>
					<div class="row">
						<div class="col-xs-10">
							<h4><?php echo $locales[$desc->locale]; ?></h4>
							<p><?php echo $desc->text; ?></p>
						</div>
					</div>
					<div class="clearfix"></div><br><br>
					<?php endforeach; ?>
					<div class="alert alert-warning text-center">
						<h2><i class="fa fa-info-circle"></i></h2>
						<?php echo $this->translate('If you delete this video all descriptions of this video will be deleted'); ?>
					</div>
					<?php endif; ?>
					<form action="" method="post">
						<button class="btn btn-danger" type="submit">
							<i class="fa fa-trash"></i>
							<?php echo $this->translate('Delete'); ?>
						</button>
						<a href="<?php echo $this->url('admin/media', array('locale' => $this->currentLocale(), 'action' => 'videos')) ?>" class="btn btn-default">
							<i class="fa fa-remove"></i>
							<?php echo $this->translate('Cancel'); ?>
						</a>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
	$('.delete-desc-btn').click(function() {
		if ( ! confirm("<?php echo $this->translate('Do you want to delete this description ?'); ?>"))
			return false;
	});
</script>