<?php echo $this->headTitle()->append($this->translate('Edit images collection'))->append($this->translate('Media')) ?>
<?php $mediaConfig = $this->getHelperPluginManager()->getServiceLocator()->get('config')['media']; ?>
<div class="row wrapper border-bottom white-bg page-heading">
	<div class="col-sm-8">
		<h2><?php echo $this->translate('Edit images collection') ?></h2>
		<?php
			$this->plugin('navigation')->setContainer($this->navigation('Zend\Navigation\Admin')->getContainer());

			echo $this->navigation()
					  ->breadcrumbs()
					  ->setMinDepth(0)               
					  ->setMaxDepth(4)         
					  ->setPartial('partial/admin-breadcrumbs');
		?>
	</div>
	<div class="col-sm-4">
		<div class="title-action">
			<a href="<?php echo $this->url('admin/media', array('locale' => $this->currentLocale(), 'action' => 'collections')); ?>" class="btn btn-primary">
				<i class="fa fa-check"></i>
				<?php echo $this->translate('Done'); ?>
			</a>
		</div>
	</div>
</div>
<div class="wrapper wrapper-content">   
	<?php if ($this->collection->count() > 0) : ?>
	<div class="row">
		<div class="col-xs-12">
			<div class="ibox float-e-margins">
				<div class="ibox-title">
					<h5><?php echo $this->translate('Uploaded images'); ?></h5>
				</div>
				<div class="ibox-content">
					<?php foreach ($this->collection as $cn) : ?>
						<?php $src = $mediaConfig['public_path'] . "collection_" . $cn->name . "/" . $cn->src; ?>
						<div class="img-wrapper">
							<img src="<?php echo $this->basePath($src); ?>" alt="" class="img-responsive img-thumbnail">
							<span class="controls">
								<a href="<?php echo $this->url('admin/media', array('locale' => $this->currentLocale(), 'action' => 'editImage', 'collection' => $cn->name, 'id' => $cn->id)); ?>" class="edit-btn">
									<span class="fa fa-fw fa-pencil"></span>
								</a><a href="<?php echo $this->url('admin/media', array('locale' => $this->currentLocale(), 'action' => 'deleteImage', 'collection' => $cn->name, 'id' => $cn->id)); ?>" class="delete-btn">
									<span class="fa fa-fw fa-trash"></span>
								</a>
							</span>
						</div>
					<?php endforeach; ?>
					<div class="alert alert-warning text-center">
						<h2><i class="fa fa-info-circle"></i></h2>
						<?php echo $this->translate('If you delete all images in collection, collection and galleries connected with collection will be deleted automatically'); ?>
					</div>
				</div>
			</div>
		</div>
	</div>
	<?php endif; ?>
	<div class="row">
		<div class="col-md-12">
			<div id="fine-uploader-gallery"></div>
		</div>
	</div>
</div>
<script type="text/template" id="qq-template-gallery">
	<div class="qq-uploader-selector qq-uploader qq-gallery" qq-drop-area-text="Drop files here" style="background-color: white;">
		<div class="qq-total-progress-bar-container-selector qq-total-progress-bar-container">
			<div role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" class="qq-total-progress-bar-selector qq-progress-bar qq-total-progress-bar"></div>
		</div>
		<div class="qq-upload-drop-area-selector qq-upload-drop-area" qq-hide-dropzone>
			<span class="qq-upload-drop-area-text-selector"></span>
		</div>
		<div class="qq-upload-button-selector qq-upload-button">
			<div>Upload a file</div>
		</div>
		<span class="qq-drop-processing-selector qq-drop-processing">
			<span>Processing dropped files...</span>
			<span class="qq-drop-processing-spinner-selector qq-drop-processing-spinner"></span>
		</span>
		<ul class="qq-upload-list-selector qq-upload-list" role="region" aria-live="polite" aria-relevant="additions removals">
			<li>
				<span role="status" class="qq-upload-status-text-selector qq-upload-status-text"></span>
				<div class="qq-progress-bar-container-selector qq-progress-bar-container">
					<div role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" class="qq-progress-bar-selector qq-progress-bar"></div>
				</div>
				<span class="qq-upload-spinner-selector qq-upload-spinner"></span>
				<div class="qq-thumbnail-wrapper">
					<img class="qq-thumbnail-selector" qq-max-size="120" qq-server-scale>
				</div>
				<button type="button" class="qq-upload-cancel-selector qq-upload-cancel">X</button>
				<button type="button" class="qq-upload-retry-selector qq-upload-retry">
					<span class="qq-btn qq-retry-icon" aria-label="Retry"></span>
					Retry
				</button>

				<div class="qq-file-info">
					<div class="qq-file-name">
						<span class="qq-upload-file-selector qq-upload-file"></span>
						<span class="qq-edit-filename-icon-selector qq-edit-filename-icon" aria-label="Edit filename"></span>
					</div>
					<input class="qq-edit-filename-selector qq-edit-filename" tabindex="0" type="text">
					<span class="qq-upload-size-selector qq-upload-size"></span>
					<button type="button" class="qq-btn qq-upload-delete-selector qq-upload-delete">
						<span class="qq-btn qq-delete-icon" aria-label="Delete"></span>
					</button>
					<button type="button" class="qq-btn qq-upload-pause-selector qq-upload-pause">
						<span class="qq-btn qq-pause-icon" aria-label="Pause"></span>
					</button>
					<button type="button" class="qq-btn qq-upload-continue-selector qq-upload-continue">
						<span class="qq-btn qq-continue-icon" aria-label="Continue"></span>
					</button>
				</div>
			</li>
		</ul>

		<dialog class="qq-alert-dialog-selector">
			<div class="qq-dialog-message-selector"></div>
			<div class="qq-dialog-buttons">
				<button type="button" class="qq-cancel-button-selector">Close</button>
			</div>
		</dialog>

		<dialog class="qq-confirm-dialog-selector">
			<div class="qq-dialog-message-selector"></div>
			<div class="qq-dialog-buttons">
				<button type="button" class="qq-cancel-button-selector">No</button>
				<button type="button" class="qq-ok-button-selector">Yes</button>
			</div>
		</dialog>

		<dialog class="qq-prompt-dialog-selector">
			<div class="qq-dialog-message-selector"></div>
			<input type="text">
			<div class="qq-dialog-buttons">
				<button type="button" class="qq-cancel-button-selector">Cancel</button>
				<button type="button" class="qq-ok-button-selector">Ok</button>
			</div>
		</dialog>
	</div>
</script>
<?php 
	$this->headlink()
	->appendStylesheet('css/plugins/fine-uploader/fine-uploader-gallery.min.css');

	$this->headScript()
	->appendFile($this->basePath('js/plugins/fine-uploader/fine-uploader.min.js'));

	$this->inlineScript()
	->appendScript("	
		var galleryUploader = new qq.FineUploader({
			element: document.getElementById(\"fine-uploader-gallery\"),
			template: 'qq-template-gallery',
			request: {
				endpoint: '".$this->url('admin/media', array('locale' => $this->currentLocale(), 'action' => 'upload'))."'
			},
			thumbnails: {
				placeholders: {
					waitingPath: 'img/fine-uploader/placeholders/waiting-generic.png',
					notAvailablePath: 'img/fine-uploader/placeholders/not_available-generic.png'
				}
			},
			validation: {
				allowedExtensions: ['jpeg', 'jpg', 'gif', 'png']
			}
		});
	");
?>