<?php  
	$this->headTitle()->append($this->translate('Typo'));
?>
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-sm-4">
        <h2><?php echo $this->translate('Typo reports') ?></h2>
        <?php
            $this->plugin('navigation')->setContainer($this->navigation('Zend\Navigation\Admin')->getContainer());

            echo $this->navigation()
                      ->breadcrumbs()
                      ->setMinDepth(0)               
                      ->setMaxDepth(4)         
                      ->setPartial('partial/admin-breadcrumbs');
        ?>
    </div>
</div>
<div class="wrapper wrapper-content">
	<?php if($this->reports): ?>
		<div class="row">
			<div class="col-lg-12">
				<div class="ibox float-e-margins">
					<div class="ibox-title">
						<h5><?php echo $this->translate('Reports') ?></h5>
					</div>
					<div class="ibox-content table-reponsive">
						<table class="table datatable">
							<thead>
								<tr>
									<td>#</td>
									<td><?php echo $this->translate('URL') ?></td>
									<td><?php echo $this->translate('Typo') ?></td>
									<td><?php echo $this->translate('Reporter comment') ?></td>
									<td><?php echo $this->translate('Reported date') ?></td>
									<td></td>
								</tr>
							</thead>
							<tbody>
								<?php $i=1; foreach ($this->reports as $report): ?>
									<tr>
										<td><?php echo $i ?></td>
										<td>
											<a target="_blank" href="<?php echo $report->url ?>"><?php echo $report->url ?></a>
										</td>
										<td><?php echo $report->text ?></td>
										<td><?php echo $report->comment ?></td>
										<td>
											<?php
												echo date('d-m-Y', $report->reported_in);
											?>
				                        </td>
										<td class="text-right">
											<a class="btn btn-success btn-rounded btn-outline" data-toggle="tooltip" data-placement="top" data-original-title="<?php echo $this->escapeHtmlAttr($this->translate('Corrected')) ?>" href="<?php echo $this->url('admin/typo-report', array('locale' => $this->currentLocale(), 'action' => 'correct', 'id' => $report->id)) ?>">
												<i class="fa fa-check"></i>
											</a>
										</td>
									</tr>
								<?php $i++; endforeach ?>
							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
	<?php else: ?>
		<div class="middle-box text-center alert alert-success">
			<p>
				<i class="fa fa-check fa-3x"></i>
			</p>
	        <h3 class="font-bold"><?php echo $this->translate('Nothing reported yet') ?></h3>
	        <div class="error-desc">
	            <?php echo $this->translate('Or your app doesn\'t contain any typo good job!') ?>
	            <br><br>
	        </div>
	    </div>
	<?php endif ?>
</div>
<script src="js/plugins/dataTables/jquery.dataTables.js"></script>
<script src="js/plugins/dataTables/dataTables.bootstrap.js"></script>
<script src="js/plugins/dataTables/dataTables.responsive.js"></script>
<script src="js/plugins/dataTables/dataTables.tableTools.min.js"></script>
<?php  
	$this->headStyle()
	->appendStyle("
		.white--space-nowrap
		{
			white-space: nowrap;
		}
	");

	$this->headLink()
	->appendStylesheet($this->basePath('css/plugins/dataTables/dataTables.bootstrap.css'))
	->appendStylesheet($this->basePath('css/plugins/dataTables/dataTables.responsive.css'))
	->appendStylesheet($this->basePath('css/plugins/dataTables/dataTables.tableTools.min.css'))
	->appendStylesheet($this->basePath('css/plugins/dataTables/dataTables.custom.css'));

	$this->inlineScript()
	->appendFile($this->basePath('js/plugins/dataTables/jquery.dataTables.js'))
	->appendFile($this->basePath('js/plugins/dataTables/dataTables.bootstrap.js'))
	->appendFile($this->basePath('js/plugins/dataTables/dataTables.responsive.js'))
	->appendFile($this->basePath('js/plugins/dataTables/dataTables.tableTools.min.js'))
	->appendScript("
		$('.datatable').dataTable({
            //'responsive': true,
            'language': {
                'url': '".$this->url('application/default', array('locale' => $this->currentLocale(), 'controller' => 'jsPlugins', 'action' => 'datatablesI18n'))."'
            }
        });
		$('*[data-toggle=\"tooltip\"]').tooltip();
	");
?>