{
    "sEmptyTable":     "<?php echo $this->escapeHtmlAttr($this->translate("No data available in table")) ?>",
    "sInfo":           "<?php echo $this->escapeHtmlAttr($this->translate("Showing _START_ to _END_ of _TOTAL_ entries")) ?>",
    "sInfoEmpty":      "<?php echo $this->escapeHtmlAttr($this->translate("Showing 0 to 0 of 0 entries")) ?>",
    "sInfoFiltered":   "<?php echo $this->escapeHtmlAttr($this->translate("(filtered from _MAX_ total entries)")) ?>",
    "sInfoPostFix":    "<?php echo $this->escapeHtmlAttr($this->translate("")) ?>",
    "sInfoThousands":  "<?php echo $this->escapeHtmlAttr($this->translate(",")) ?>",
    "sLengthMenu":     "<?php echo $this->escapeHtmlAttr($this->translate("Show _MENU_ entries")) ?>",
    "sLoadingRecords": "<?php echo $this->escapeHtmlAttr($this->translate("Loading...")) ?>",
    "sProcessing":     "<?php echo $this->escapeHtmlAttr($this->translate("Processing...")) ?>",
    "sSearch":         "<?php echo $this->escapeHtmlAttr($this->translate("Search:")) ?>",
    "sZeroRecords":    "<?php echo $this->escapeHtmlAttr($this->translate("No matching records found")) ?>",
    "oPaginate": {
        "sFirst":    "<?php echo $this->escapeHtmlAttr($this->translate("First")) ?>",
        "sLast":     "<?php echo $this->escapeHtmlAttr($this->translate("Last")) ?>",
        "sNext":     "<?php echo $this->escapeHtmlAttr($this->translate("Next")) ?>",
        "sPrevious": "<?php echo $this->escapeHtmlAttr($this->translate("Previous")) ?>"
    },
    "oAria": {
        "sSortAscending":  "<?php echo $this->escapeHtmlAttr($this->translate(": activate to sort column ascending")) ?>",
        "sSortDescending": "<?php echo $this->escapeHtmlAttr($this->translate(": activate to sort column descending")) ?>"
    }
}