<?php  
    echo $this->headTitle()->append($this->translate('Videos'));
    echo $this->headStyle()
    ->appendStyle("
        .video {
            position: relative !important;
        }

        .video:before {
            content: ' ';
            display: block;
            position: absolute;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
        }
    ");
?>
<div class="bg-color-sky-light">
    <div class="content-sm container">
        <div class="row">
            <div class="col-md-12 md-margin-b-50">
                <ol class="breadcrumb">
                    <li>
                        <a href="<?php echo $this->url('home-locale', array('locale' => $this->currentLocale())) ?>">
                            <?php echo $this->translate('Home') ?>
                        </a>
                    </li>
                    <li class="active"><?php echo $this->translate('Videos'); ?></li>
                </ol>
            </div>
            <div class="clearfix"></div>

            <div class="col-md-12 md-margin-b-50">
                <article class="blog-grid margin-b-30">
                    <div class="blog-grid-content">
                        <h2 class="blog-grid-title-lg">
                            <?php echo $this->translate('Videos'); ?>
                        </h2>

<div id="videos">
    <?php $i=0; foreach ($this->videos as $video) : ?>
    <?php $video->src = preg_replace('/(width|height)=\"[0-9]+\"/', '$1="100%"', str_replace('<iframe ', '<iframe class="embed-responsive-item"', $video->src)); ?>

    <div id="video<?php echo $i ?>" class="col-xs-12" style="background-color: #343434;padding-top: 10px;padding-bottom: 10px;">
        <div class="row">
            <div class="col-sm-4 description" style="padding-left: 5px;">
                <h3 class="text-left" style="color:#F8F8F8;margin: 0;margin-left: 5px;">
                    <?php echo $this->descriptions[$video->id]->text ?>
                </h3>
            </div>

            <div class="col-sm-8 img-responsive center-block video">
                <div class="embed-responsive embed-responsive-16by9">
                    <?php echo $video->src; ?>
                </div>
            </div>
        </div>
    </div>

    <div class="clearfix"></div><br>
    <?php $i++; endforeach; ?>
</div>
                    </div>
                </article>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    $(window).load(function(){
        $('.video').click(function(){
            $($(this).attr('data-video')).slideDown(400);
        });             
    });
</script>